// Romanised Thai (draft; tone marks; RTGS-like syllables joined with hyphens). Key = the exact Thai string as used in the game.
export const ROM = {
  'เดินเข้าเซเว่นกลางกรุงเทพฯ แล้วสำรวจทุกชั้นวางสินค้า': 'dəən-kâo sé-wên glaang grung-têep láeo sǎm-rùuat túk chán waang sǐn-káa',
  'เดินเข้าร้าน': 'dəən-kâo ráan',
  'กำลังจัดสินค้าขึ้นชั้น…': 'gam-lang jàt sǐn-káa kʉ̂n chán…',
  'พร้อมแล้ว!': 'prɔ́ɔm láeo!',
  'ตั้งค่า': 'dtâng-kâa',
  'ปุ่มควบคุม': 'bpùm kûuap-kum',
  'เกี่ยวกับเกม': 'gìiao-gàp geem',
  'ภาษา': 'paa-sǎa',
  'แนะนำให้ใส่หูฟังและเล่นแบบเต็มจอ กด L เพื่อสลับภาษาได้ทุกเมื่อ': 'náe-nam hâi sài hǔu-fang láe lên bàep dtem-jɔɔ gòt L pʉ̂a sà-làp paa-sǎa dâai túk mʉ̂a',
  'ทั้งป้าย บรรจุภัณฑ์ และป้ายราคา จะเปลี่ยนภาษาตาม': 'táng bpâai ban-jù-pan láe bpâai raa-kaa jà bplìian paa-sǎa dtaam',
  'เล่นต่อ': 'lên dtɔ̀ɔ',
  'ไทย': 'tai',
  'EN + ไทย': 'EN + tai',
  'หยุดชั่วคราว': 'yùt chûa-kraao',
  'สมุดสะสมสินค้า': 'sà-mùt sà-sǒm sǐn-káa',
  'รายการซื้อของ': 'raai-gaan sʉ́ʉ kɔ̌ɔng',
  'กลับหน้าหลัก': 'glàp nâa làk',
  'กลับ': 'glàp',
  'ปิด': 'bpìt',
  'คลิกเพื่อเล่นต่อ': 'klík pʉ̂a lên dtɔ̀ɔ',
  'เปลี่ยนภาษาของป้าย บรรจุภัณฑ์ ป้ายราคา และเมนูทั้งหมด': 'bplìian paa-sǎa kɔ̌ɔng bpâai ban-jù-pan bpâai raa-kaa láe mee-nuu táng-mòt',
  'ช่วงเวลา': 'chûuang wee-laa',
  'ให้เวลาเดินต่อ': 'hâi wee-laa dəən dtɔ̀ɔ',
  'คุณภาพกราฟิก': 'kun-na-pâap graa-fík',
  'ต่ำ': 'dtàm',
  'กลาง': 'glaang',
  'สูง': 'sǔung',
  'มุมมอง (FOV)': 'mum-mɔɔng (FOV)',
  'ความไวเมาส์': 'kwaam wai mao',
  'กลับทิศแกนแนวตั้ง': 'glàp tít gaen naao dtâng',
  'กล้องโยกตามการเดิน': 'glɔ̂ng yôok dtaam gaan dəən',
  'ระดับเสียงรวม': 'rá-dàp sǐiang ruuam',
  'เสียงบรรยากาศ': 'sǐiang ban-yaa-gàat',
  'เพลงในร้าน': 'pleeng nai ráan',
  'เสียงเอฟเฟกต์': 'sǐiang éf-fék',
  'คำบรรยาย': 'kam ban-yaai',
  'เสียงพนักงาน (ภาษาไทย ถ้าเบราว์เซอร์รองรับ)': 'sǐiang pá-nák-ngaan (paa-sǎa tai tâa braao-sə̂ə rɔɔng-ráp)',
  'แสดงคำแนะนำปุ่ม': 'sà-daeng kam-náe-nam bpùm',
  'แสดงคำอ่านภาษาไทย': 'sà-daeng kam-àan paa-sǎa tai',
  'รีเซ็ตความคืบหน้า': 'rii-sét kwaam-kʉ̂ʉp-nâa',
  'รีเซ็ตสมุดสะสม ภารกิจ และกระเป๋าเงิน?': 'rii-sét sà-mùt sà-sǒm paa-rá-gìt láe grà-bpǎo ngən?',
  'เช้า 07:30': 'cháao 07:30',
  'เที่ยง 12:30': 'thîiang 12:30',
  'บ่าย 15:30': 'bàai 15:30',
  'เย็น 18:30': 'yen 18:30',
  'กลางคืน 21:30': 'glaang-kʉʉn 21:30',
  'ดึก 02:00': 'dʉ̀k 02:00',
  'เดิน': 'dəən',
  'มองรอบตัว': 'mɔɔng rɔ̂ɔp dtuua',
  'วิ่ง': 'wîng',
  'ย่อตัว (ดูชั้นล่าง)': 'yɔ̂ɔ dtuua (duu chán lâang)',
  'ซูมอ่านฉลาก': 'suum àan chà-làak',
  'หยิบ / ใช้งาน': 'yìp / chái-ngaan',
  'ดูใกล้ๆ': 'duu glâi-glâi',
  'วางสินค้าคืน': 'waang sǐn-káa kʉʉn',
  'พลิกหน้า/หลังซอง (ตอนดูใกล้ๆ)': 'plík nâa/lǎng sɔɔng (dtɔɔn duu glâi-glâi)',
  'สลับภาษา': 'sà-làp paa-sǎa',
  'ตะกร้า': 'dtà-grâa',
  'หยุด / เมนู': 'yùt / mee-nuu',
  'เปิด/ปิดคำแนะนำ': 'bpə̀ət/bpìt kam-náe-nam',
  'หยิบ': 'yìp',
  'วางคืน': 'waang kʉʉn',
  'ใช้งาน': 'chái-ngaan',
  'เปิด': 'bpə̀ət',
  'คุยด้วย': 'kui dûuai',
  'เงินสด': 'ngən-sòt',
  'บัญชี': 'ban-chii',
  'ในมือ': 'nai mʉʉ',
  'สมุดสะสม': 'sà-mùt sà-sǒm',
  'ข้างนอก': 'kâang-nɔ̂ɔk',
  'ในร้าน': 'nai ráan',
  'มือเต็มแล้ว! หยิบตะกร้าตรงประตูก่อนนะ': 'mʉʉ dtem láeo! yìp dtà-grâa dtrong bprà-dtuu gɔ̀ɔn ná',
  'ตะกร้าเต็มแล้ว': 'dtà-grâa dtem láeo',
  'หยิบตะกร้า': 'yìp dtà-grâa',
  'วางตะกร้าคืน': 'waang dtà-grâa kʉʉn',
  'หยิบตะกร้าแล้ว': 'yìp dtà-grâa láeo',
  'หยิบแล้ว: {name}': 'yìp láeo: {name}',
  'วางคืนแล้ว: {name}': 'waang kʉʉn láeo: {name}',
  'ไม่มีสินค้าให้วางคืน': 'mâi mii sǐn-káa hâi waang kʉʉn',
  'พบสินค้าใหม่ในสมุดสะสม!': 'póp sǐn-káa mài nai sà-mùt sà-sǒm!',
  'ตอนนี้ขายเครื่องดื่มแอลกอฮอล์ไม่ได้ (กฎหมายไทย: 11.00–14.00 น. และ 17.00–24.00 น. เท่านั้น)': 'dtɔɔn-níi kǎai krʉ̂ang-dʉ̀ʉm aen-gɔɔ-hɔɔ mâi dâai (gòt-mǎai tai: 11.00–14.00 nɔɔ láe 17.00–24.00 nɔɔ tâo-nán)',
  'บุหรี่ต้องเก็บมิดชิดตามกฎหมายไทย ต้องสอบถามพนักงาน (อายุ 20 ปีขึ้นไป)': 'bù-rìi dtɔ̂ng gèp mít-chít dtaam gòt-mǎai tai dtɔ̂ng sɔ̀ɔp-tǎam pá-nák-ngaan (aa-yú 20 bpii kʉ̂n-bpai)',
  'สแกน': 'sà-gaen',
  'กิโลแคลอรี': 'gì-loo-kae-lɔɔ-rîi',
  'ข้างนอก {t}°C · ในร้าน {i}°C': 'kâang-nɔ̂ɔk {t}°C · nai ráan {i}°C',
  'เข้าสู่': 'kâo sùu',
  'ราคา': 'raa-kaa',
  'รวม': 'ruuam',
  '{n} ชิ้น': '{n} chín',
  '1 ชิ้น': '1 chín',
  'WASD เดิน · Shift วิ่ง · C ย่อ · Z ซูม': 'WASD dəən · Shift wîng · C yɔ̂ɔ · Z suum',
  'E หยิบ · F ดูใกล้ๆ · G วางคืน · L สลับภาษา': 'E yìp · F duu glâi-glâi · G waang kʉʉn · L sà-làp paa-sǎa',
  'B ตะกร้า · P สมุดสะสม · Q รายการ · Esc เมนู': 'B dtà-grâa · P sà-mùt sà-sǒm · Q raai-gaan · Esc mee-nuu',
  'เดินไปที่ประตูกระจก ประตูจะเปิดเองอัตโนมัติ': 'dəən bpai tîi bprà-dtuu grà-jòok bprà-dtuu jà bpə̀ət eeng àt-dtà-noo-mát',
  'ยี่ห้อ': 'yîi-hɔ̂',
  'ปริมาณสุทธิ': 'bpà-rí-maan sùt-tí',
  'ส่วนประกอบ': 'sùuan bprà-gɔ̀ɔp',
  'มีส่วนผสมของ': 'mii sùuan pà-sǒm kɔ̌ɔng',
  'เกร็ดน่ารู้': 'grèt nâa-rúu',
  'วางอยู่ที่': 'waang yùu tîi',
  'หมวดสินค้า': 'mùuat sǐn-káa',
  'พลิก': 'plík',
  'ขยับเมาส์เพื่อหมุน': 'kà-yàp mao pʉ̂a mǔn',
  'วางลง': 'waang long',
  'อุ่นไมโครเวฟได้': 'ùn mai-kroo-wéep dâai',
  'แอลกอฮอล์ · 20 ปีขึ้นไป': 'aen-gɔɔ-hɔɔ · 20 bpii kʉ̂n-bpai',
  'ด้านหน้า': 'dâan nâa',
  'ด้านหลัง': 'dâan lǎng',
  'อร่อย!': 'à-rɔ̀i!',
  'มองดู หยิบ หรือซื้อสินค้าเพื่อบันทึกลงสมุด': 'mɔɔng-duu yìp rʉ̌ʉ sʉ́ʉ sǐn-káa pʉ̂a ban-tʉk long sà-mùt',
  'พบแล้ว {a} / {b}': 'póp láeo {a} / {b}',
  'ทั้งหมด': 'táng-mòt',
  'ยังไม่พบ — สำรวจต่อไป!': 'yang mâi póp — sǎm-rùuat dtɔ̀ɔ-bpai!',
  'ค้นหาสินค้า…': 'kón-hǎa sǐn-káa…',
  'แสดงทั้งหมด': 'sà-daeng táng-mòt',
  'ซ่อนที่ยังไม่พบ': 'sɔ̂ɔn tîi yang mâi póp',
  'เลือกภารกิจ': 'lʉ̂ʉak paa-rá-gìt',
  'ภารกิจปัจจุบัน': 'paa-rá-gìt bpàt-jù-ban',
  'ภารกิจสำเร็จ!': 'paa-rá-gìt sǎm-rèt!',
  'รางวัล: +{n} แต้ม 11 Club': 'raang-wan: +{n} dtɛ̂ɛm 11 Club',
  'ยกเลิกภารกิจ': 'yók-lə̂ək paa-rá-gìt',
  'เริ่ม': 'rə̂əm',
  'ยังไม่มีภารกิจ กด Q เพื่อเลือก': 'yang mâi mii paa-rá-gìt gòt Q pʉ̂a lʉ̂ʉak',
  'ซื้อ': 'sʉ́ʉ',
  'อะไรก็ได้': 'à-rai gɔ̂ɔ dâai',
  'ตะกร้าของคุณ': 'dtà-grâa kɔ̌ɔng kun',
  'ยังว่างอยู่ ไปเดินดูสินค้ากันเถอะ!': 'yang wâang yùu bpai dəən duu sǐn-káa gan tə̀',
  'รวมเป็นเงิน': 'ruuam bpen ngən',
  'นำไปชำระเงินที่เคาน์เตอร์แคชเชียร์': 'nam bpai cham-rá ngən tîi kao-dtə̂ə káet-chîia',
  'สินค้าที่ซื้อแล้ว': 'sǐn-káa tîi sʉ́ʉ láeo',
  'ทาน/ใช้': 'taan/chái',
  'แคชเชียร์': 'káet-chîia',
  'ชำระเงิน': 'cham-rá ngən',
  'ตะกร้าของคุณยังว่างอยู่': 'dtà-grâa kɔ̌ɔng kun yang wâang yùu',
  'ค่ะ/ครับ': 'kâ/kráp',
  'ไม่ต้อง': 'mâi dtɔ̂ng',
  'อุ่นด้วย': 'ùn dûuai',
  'ไม่ต้องอุ่น': 'mâi dtɔ̂ng ùn',
  'ขอถุงด้วย': 'kɔ̌ɔ tǔng dûuai',
  'ไม่รับถุง': 'mâi ráp tǔng',
  'ขอด้วย': 'kɔ̌ɔ dûuai',
  'มี (สแกนแอป)': 'mii (sà-gaen áep)',
  'ไม่มี': 'mâi mii',
  'ชำระเงินด้วยวิธีไหน?': 'cham-rá ngən dûuai wí-tii nǎi?',
  'พร้อมเพย์ (QR)': 'prɔ́ɔm-pee (QR)',
  'ทรูมันนี่ วอลเล็ท': 'truu-man-nîi wɔɔn-lét',
  'เงินไม่พอสำหรับวิธีชำระนี้': 'ngən mâi pɔɔ sǎm-ràp wí-tii cham-rá níi',
  'สแกน QR ด้วยแอปธนาคารของคุณ': 'sà-gaen QR dûuai áep tá-naa-kaan kɔ̌ɔng kun',
  'สแกนเพื่อจ่าย': 'sà-gaen pʉ̂a jàai',
  'ชำระเงินเรียบร้อย': 'cham-rá ngən rîiap-rɔ́ɔi',
  'เงินทอน': 'ngən-tɔɔn',
  'รับเงินมา': 'ráp ngən maa',
  'ยอดรวม': 'yɔ̂ɔt ruuam',
  'ยกเลิก': 'yók-lə̂ək',
  'ใบเสร็จ': 'bai-sèt',
  'บันทึกใบเสร็จเป็นรูป': 'ban-tʉk bai-sèt bpen rûup',
  'เดินต่อ': 'dəən dtɔ̀ɔ',
  '+{n} แต้ม 11 Club': '+{n} dtɛ̂ɛm 11 Club',
  'โบนัสรักษ์โลกที่ไม่รับถุง!': 'boo-nát rák-lôok tîi mâi ráp tǔng!',
  'ยื่นบัตรประชาชน': 'yʉ̂ʉn bàt bprà-chaa-chon',
  'ชำระ ฿{n}': 'cham-rá ฿{n}',
  'พนักงานขอตรวจบัตรประชาชนสำหรับสินค้าที่จำกัดอายุ': 'pá-nák-ngaan kɔ̌ɔ dtrùuat bàt bprà-chaa-chon sǎm-ràp sǐn-káa tîi jam-gàt aa-yú',
  'บริษัท ซีพี ออลล์ จำกัด (มหาชน)': 'bɔɔ-rí-sàt sii-pii ɔɔn jam-gàt (má-hǎa-chon)',
  'สาขา: 07711 ซอยสุขุมวิท': 'sǎa-kǎa: 07711 sɔɔi sù-kǔm-wít',
  'ใบเสร็จรับเงิน/ใบกำกับภาษีอย่างย่อ': 'bai-sèt ráp ngən/bai-gam-gàp paa-sǐi yàang yɔ̂ɔ',
  'เลขประจำตัวผู้เสียภาษี': 'lêek bprà-jam-dtuua pûu sǐia paa-sǐi',
  'จำนวน': 'jam-nuuan',
  'รายการ': 'raai-gaan',
  'จำนวนเงิน': 'jam-nuuan ngən',
  'รวมเงิน': 'ruuam ngən',
  'ภาษีมูลค่าเพิ่ม 7% (รวมแล้ว)': 'paa-sǐi muun-lá-kâa pə̂əm 7% (ruuam láeo)',
  'ยอดสุทธิ': 'yɔ̂ɔt sùt-tí',
  'พร้อมเพย์': 'prɔ́ɔm-pee',
  'ทรูมันนี่': 'truu-man-nîi',
  'แต้ม 11 Club ที่ได้รับ': 'dtɛ̂ɛm 11 Club tîi dâai-ráp',
  'ขอบคุณที่ใช้บริการ': 'kɔ̀ɔp-kun tîi chái bɔɔ-rí-gaan',
  'สะดวกทุกที่ ทุกเวลา': 'sà-dùuak túk tîi túk wee-laa',
  'พนักงาน': 'pá-nák-ngaan',
  'เครื่อง POS': 'krʉ̂ang POS',
  'อุ่นแล้ว': 'ùn láeo',
  'ปลดล็อกความสำเร็จ': 'bplòt-lɔ́k kwaam-sǎm-rèt',
  'สวัสดี!': 'sà-wàt-dii!',
  'เดินเข้าร้านเป็นครั้งแรก': 'dəən-kâo ráan bpen kráng-rɛ̂ɛk',
  'สองภาษา': 'sɔ̌ɔng paa-sǎa',
  'สลับภาษาระหว่างอ่านซองสินค้า': 'sà-làp paa-sǎa rá-wàang àan sɔɔng sǐn-káa',
  'ตะกร้าเต็ม': 'dtà-grâa dtem',
  'ใส่สินค้า 10 ชิ้นในตะกร้า': 'sài sǐn-káa 10 chín nai dtà-grâa',
  'นักสำรวจเซเว่น': 'nák-sǎm-rùuat sé-wên',
  'พบสินค้า 25 ชนิด': 'póp sǐn-káa 25 chá-nít',
  'สมุดสะสมครบเซ็ต': 'sà-mùt sà-sǒm króp sét',
  'พบสินค้าครบทุกชนิดในร้าน': 'póp sǐn-káa króp túk chá-nít nai ráan',
  'ติ๊ง!': 'dtîng!',
  'ให้พนักงานอุ่นอาหารในไมโครเวฟ': 'hâi pá-nák-ngaan ùn aa-hǎan nai mai-kroo-wéep',
  'สแกนจ่าย': 'sà-gaen jàai',
  'จ่ายเงินด้วย QR พร้อมเพย์': 'jàai ngən dûuai QR prɔ́ɔm-pee',
  'เพื่อนสี่ขาหน้าร้าน': 'pʉ̂an sìi kǎa nâa ráan',
  'ทักทายน้องหมาขี้เซาหน้าร้าน': 'ták-taai nɔ́ɔng-mǎa kîi-sao nâa ráan',
  'นักช้อปรักษ์โลก': 'nák-chɔ́ɔp rák-lôok',
  'ไม่รับถุงตอนชำระเงิน': 'mâi ráp tǔng dtɔɔn cham-rá ngən',
  'ตู้เอทีเอ็ม': 'dtûu ee-tii-em',
  'ถอนเงินจากตู้เอทีเอ็ม': 'tɔ̌ɔn ngən jàak dtûu ee-tii-em',
  'ซื้อของดึก': 'sʉ́ʉ kɔ̌ɔng dʉ̀k',
  'ซื้อของช่วงเที่ยงคืนถึงตีห้า': 'sʉ́ʉ kɔ̌ɔng chûuang tîiang-kʉʉn tʉ̌ng dtii-hâa',
  'ภารกิจสำเร็จ': 'paa-rá-gìt sǎm-rèt',
  'ทำภารกิจซื้อของสำเร็จ': 'tam paa-rá-gìt sʉ́ʉ kɔ̌ɔng sǎm-rèt',
  'ถอนเงิน ฿500': 'tɔ̌ɔn ngən ฿500',
  'ถอนเงิน ฿500 แล้ว': 'tɔ̌ɔn ngən ฿500 láeo',
  'วันนี้ไม่มีค่าธรรมเนียม': 'wan-níi mâi mii kâa tam-niiam',
  'วันนี้ถอนเต็มวงเงินแล้ว': 'wan-níi tɔ̌ɔn dtem wong-ngən láeo',
  'ซอยสุขุมวิท กรุงเทพฯ': 'sɔɔi sù-kǔm-wít grung-têep',
  'ทางเข้า': 'taang-kâo',
  'เคาน์เตอร์แคชเชียร์': 'kao-dtə̂ə káet-chîia',
  'บะหมี่กึ่งสำเร็จรูป': 'bà-mìi gʉ̀ng sǎm-rèt-rûup',
  'ขนมขบเคี้ยว': 'kà-nǒm kòp-kíiao',
  'ขนมหวานและบิสกิต': 'kà-nǒm wǎan láe bìt-sà-gìt',
  'ของใช้ในบ้านและของใช้ส่วนตัว': 'kɔ̌ɔng-chái nai bâan láe kɔ̌ɔng-chái sùuan-dtuua',
  'ยาสามัญและสมุนไพร': 'yaa sǎa-man láe sà-mǔn-prai',
  'อาหารพร้อมทาน': 'aa-hǎan prɔ́ɔm taan',
  'ตู้แช่เครื่องดื่ม': 'dtûu châe krʉ̂ang-dʉ̀ʉm',
  'เบียร์และสุรา': 'bia láe sù-raa',
  'ตู้แช่ไอศกรีม': 'dtûu châe ai-sà-griim',
  'น้ำร้อนและไมโครเวฟ': 'nám-rɔ́ɔn láe mai-kroo-wéep',
  'ตู้เอทีเอ็มและบริการ': 'dtûu ee-tii-em láe bɔɔ-rí-gaan',
  'เบเกอรี่': 'bee-gə̂ə-rîi',
  'เคาน์เตอร์นั่งทาน': 'kao-dtə̂ə nâng taan',
  'ของแห้งและเครื่องปรุง': 'kɔ̌ɔng-hɛ̂ɛng láe krʉ̂ang-bprung',
  'อาหารร้อนและอีเลฟเว่น คาเฟ่': 'aa-hǎan rɔ́ɔn láe ii-lép-wên kaa-fêe',
  'รีเซ็ตความคืบหน้าแล้ว': 'rii-sét kwaam-kʉ̂ʉp-nâa láeo',
  'บันทึกใบเสร็จแล้ว': 'ban-tʉk bai-sèt láeo',
  'ภาษา: อังกฤษ': 'paa-sǎa: ang-grìt',
  'ภาษา: ไทย': 'paa-sǎa: tai',
  'ภาษา: อังกฤษ + ไทย': 'paa-sǎa: ang-grìt + tai',
  'น้องหมาลืมตาข้างหนึ่ง แล้วก็หลับต่อ': 'nɔ́ɔng-mǎa lʉʉm dtaa kâang nʉ̀ng láeo gɔ̂ɔ làp dtɔ̀ɔ',
  'ติ๊ง! อาหารร้อนแล้ว': 'dtîng! aa-hǎan rɔ́ɔn láeo',
  'กด F11 เพื่อเล่นเต็มจอ': 'gòt F11 pʉ̂a lên dtem-jɔɔ',
  'เงินไม่พอ — ไปหาตู้เอทีเอ็ม!': 'ngən mâi pɔɔ — bpai hǎa dtûu ee-tii-em!',
  'ภาษาและโลกในเกม': 'paa-sǎa láe lôok nai geem',
  'กราฟิก': 'graa-fík',
  'การควบคุม': 'gaan kûuap-kum',
  'เสียง': 'sǐiang',
  'การเล่นและการเข้าถึง': 'gaan-lên láe gaan-kâo-tʉ̌ng',
  'การตั้งค่ากราฟิกบางอย่างจะมีผลหลังโหลดหน้าใหม่': 'gaan dtâng-kâa graa-fík baang-yàang jà mii pǒn lǎng lòot nâa mài',
  'โหลดใหม่ตอนนี้': 'lòot mài dtɔɔn-níi',
  '7 Eleven Simulator คือจดหมายรักถึงร้านสะดวกซื้อที่ไม่เคยปิด เดินเข้าร้านจากซอยกลางกรุงเทพฯ สำรวจทุกชั้นวาง และสลับโลกทั้งใบระหว่างภาษาอังกฤษกับไทยได้': '7 Eleven Simulator kʉʉ jòt-mǎai rák tʉ̌ng ráan sà-dùuak-sʉ́ʉ tîi mâi kəəi bpìt dəən-kâo ráan jàak sɔɔi glaang grung-têep sǎm-rùuat túk chán waang láe sà-làp lôok táng bai rá-wàang paa-sǎa ang-grìt gàp tai dâai',
  'สร้างโดย Nomaditsu ด้วย three.js ทุกอย่าง ทั้งบรรจุภัณฑ์ ป้าย เสียง และใบเสร็จ ถูกสร้างสดในเบราว์เซอร์ของคุณ ไม่มีไฟล์ภายนอก': 'sâang dooi Nomaditsu dûuai three.js túk-yàang táng ban-jù-pan bpâai sǐiang láe bai-sèt tùuk sâang sòt nai braao-sə̂ə kɔ̌ɔng kun mâi mii fai pâai-nɔ̂ɔk',
  'เกมนี้ทำขึ้นเพื่อความบันเทิงและเป็นการคารวะร้านสะดวกซื้อ ไม่มีส่วนเกี่ยวข้องหรือได้รับการรับรองจากเซเว่น อีเลฟเว่น ซีพี ออลล์ หรือแบรนด์ใดๆ ชื่อสินค้าใช้เพื่อการอธิบาย งานภาพเป็นสไตล์เฉพาะตัว ข้อมูลส่วนประกอบ ที่อยู่ และเลขทะเบียนบนบรรจุภัณฑ์เป็นเพียงตัวอย่าง': 'geem níi tam-kʉ̂n pʉ̂a kwaam ban-təəng láe bpen gaan kaa-rá-wá ráan sà-dùuak-sʉ́ʉ mâi mii sùuan gìiao-kâung rʉ̌ʉ dâai-ráp gaan ráp-rɔɔng jàak sé-wên ii-lé-wên sii-pii ɔɔn rʉ̌ʉ brɛɛn dai-dai chʉ̂ʉ sǐn-káa chái pʉ̂a gaan à-tí-baai ngaan-pâap bpen sà-dtaai chà-pɔ̀ dtuua kɔ̂ɔ-muun sùuan bprà-gɔ̀ɔp tîi-yùu láe lêek tá-bpiian bon ban-jù-pan bpen pîiang dtuua-yàang',
  'ประโยคที่จะได้ยินในร้าน: สวัสดีค่ะ, อุ่นไหมคะ, รับถุงไหมคะ, ขอบคุณค่ะ': 'bprà-yòok tîi jà dâai-yin nai ráan: sà-wàt-dii kâ, ùn mǎi ká, ráp tǔng mǎi ká, kɔ̀ɔp-kun kâ',
  'เคล็ดลับ: เปิด “แสดงคำอ่านภาษาไทย” ในการตั้งค่า เพื่อดูวิธีอ่านแต่ละประโยค': 'kléd-láp: bpə̀ət “sà-daeng kam-àan paa-sǎa tai” nai gaan dtâng-kâa pʉ̂a duu wí-tii àan dtæ̀-lá bprà-yòok',
  'น้ำร้อนสำหรับบะหมี่ของคุณ': 'nám-rɔ́ɔn sǎm-ràp bà-mìi kɔ̌ɔng kun',
  'ไมโครเวฟ': 'mai-kroo-wéep',
  'น้ำร้อน': 'nám-rɔ́ɔn',
  'เครื่องอีเลฟเว่น คาเฟ่': 'krʉ̂ang ii-lép-wên kaa-fêe',
  'น้องหมาขี้เซา': 'nɔ́ɔng-mǎa kîi-sao',
  'นั่ง': 'nâng',
  'อุ่นอาหาร': 'ùn aa-hǎan',
  'เติมน้ำร้อน': 'dtəəm nám-rɔ́ɔn',
  'สั่งเครื่องดื่ม': 'sàng krʉ̂ang-dʉ̀ʉm',
  'ทักทาย': 'ták-taai',
  'ใส่อาหารพร้อมทานในตะกร้าก่อนนะ': 'sài aa-hǎan prɔ́ɔm taan nai dtà-grâa gɔ̀ɔn ná',
  'กำลังอุ่น…': 'gam-lang ùn…',
  'อาหารที่อุ่นได้ในตะกร้าร้อนหมดแล้ว': 'aa-hǎan tîi ùn dâai nai dtà-grâa rɔ́ɔn mòt láeo',
  'ต้องมีบะหมี่ถ้วยในตะกร้าก่อน': 'dtɔ̂ng mii bà-mìi tûuai nai dtà-grâa gɔ̀ɔn',
  'เติมน้ำร้อนแล้ว รอ 3 นาทีนะ!': 'dtəəm nám-rɔ́ɔn láeo rɔɔ 3 naa-tii ná!',
  'อีเลฟเว่น คาเฟ่ — เลือกเครื่องดื่ม': 'ii-lép-wên kaa-fêe — lʉ̂ʉak krʉ̂ang-dʉ̀ʉm',
  'ขอให้อร่อยกับ{name}นะคะ!': 'kɔ̌ɔ hâi à-rɔ̀i gàp {name} ná ká!',
  'ยังไม่ได้ซื้ออะไร': 'yang mâi dâai sʉ́ʉ à-rai',
  'คุณทาน{name}อย่างเอร็ดอร่อย!': 'kun taan {name} yàang èt-à-rɔ̀i!',
  'คุณนั่งที่เคาน์เตอร์ริมกระจก มองมอเตอร์ไซค์ผ่านไปมา…': 'kun nâng tîi kao-dtə̂ə rim grà-jòok mɔɔng mɔɔ-dtəə-sai pàan bpai maa…',
  'กลางคืน': 'glaang-kʉʉn',
  'กลางวัน': 'glaang-wan',
  'ไม่จำหน่ายในเวลานี้': 'mâi jam-nàai nai wee-laa níi',
  'เวลาในเกม': 'wee-laa nai geem',
  'ประเทศไทยมีเซเว่นมากกว่า 14,000 สาขา คนไทยเรียกสั้นๆ ว่า “เซเว่น”': 'bprà-têet tai mii sé-wên mâak gwàa 14,000 sǎa-kǎa kon-tai rîiak sân-sân wâa “sé-wên”',
  'ในประเทศไทยจำหน่ายเครื่องดื่มแอลกอฮอล์ได้เฉพาะเวลา 11.00–14.00 น. และ 17.00–24.00 น. ช่วงอื่นจะมีผ้าคลุมตู้แช่': 'nai bprà-têet tai jam-nàai krʉ̂ang-dʉ̀ʉm aen-gɔɔ-hɔɔ dâai chà-pɔ́ wee-laa 11.00–14.00 nɔɔ láe 17.00–24.00 nɔɔ chûuang ʉ̀ʉn jà mii pâa klum dtûu châe',
  'บุหรี่ต้องเก็บมิดชิดหลังเคาน์เตอร์ เพราะกฎหมายไทยห้ามโชว์สินค้ายาสูบ ณ จุดขาย': 'bù-rìi dtɔ̂ng gèp mít-chít lǎng kao-dtə̂ə prɔ́ gòt-mǎai tai hâam choo sǐn-káa yaa-sùup ná jùt-kǎai',
  'ลองเมนูสุดฮิต ข้าวกะเพราไก่ไข่ดาว อุ่นไมโครเวฟก็อร่อยได้ทันที': 'lɔɔng mee-nuu sùt-hít kâao gà-prao gài kài-daao ùn mai-kroo-wéep gɔ̂ɔ à-rɔ̀i dâai tan-tii',
  '“อุ่นไหมคะ?” แปลว่า “ให้อุ่นให้ไหมคะ?” เป็นประโยคที่จะได้ยินทุกครั้งที่ไปซื้อของ': '“ùn mǎi ká?” bplɛɛ wâa “hâi ùn hâi mǎi ká?” bpen bprà-yòok tîi jà dâai-yin túk kráng tîi bpai sʉ́ʉ kɔ̌ɔng',
  'กด L เพื่อสลับระหว่างภาษาอังกฤษและไทยได้ทุกเมื่อ แม้ขณะกำลังอ่านซองสินค้า': 'gòt L pʉ̂a sà-làp rá-wàang paa-sǎa ang-grìt láe tai dâai túk mʉ̂a mɛ́ɛ kà-nà gam-lang àan sɔɔng sǐn-káa',
  'สาหร่ายทอดกรอบเป็นขนมที่นักท่องเที่ยวซื้อกลับบ้านมากที่สุดอย่างหนึ่ง': 'sǎa-ràai tɔ̂ɔt grɔ̀ɔp bpen kà-nǒm tîi nák-tɔ̂ng-tîiao sʉ́ʉ glàp bâan mâak tîi-sùt yàang nʉ̀ng',
  'แอร์เย็นฉ่ำของเซเว่นเป็นที่หลบร้อนยอดนิยมของคนกรุงเทพฯ': 'ɛɛ yen chàm kɔ̌ɔng sé-wên bpen tîi lòp-rɔ́ɔn yɔ̂ɔt-ní-yom kɔ̌ɔng kon grung-têep',
  'หมูปิ้งข้าวเหนียวคืออาหารเช้ายอดฮิตของคนกรุงเทพฯ': 'mǔu-bpîng kâao-nǐiao kʉʉ aa-hǎan cháao yɔ̂ɔt-hít kɔ̌ɔng kon grung-têep',
  'มองหารสชาติสไตล์ไทย เช่น สาหร่ายโนริ ต้มยำ ไข่เค็ม ปลาหมึกย่าง ลาบ…': 'mɔɔng-hǎa rót-châat sà-dtai tai chên sǎa-ràai noo-rii dtôm-yam kài-kem bplaa-mʉ̀k-yâang lâap…',
  'ออกไปซื้อของกินดึกๆ': 'ɔ̀ɔk bpai sʉ́ʉ kɔ̌ɔng gin dʉ̀k-dʉ̀k',
  'ดึกแล้วท้องร้อง คว้าชุดของกินดึกสุดคลาสสิกของคนกรุงเทพฯ': 'dʉ̀k láeo tɔ́ɔng rɔ́ɔng kwâa chút kɔ̌ɔng gin dʉ̀k sùt klâat-sìk kɔ̌ɔng kon grung-têep',
  'ขนมกรุบกรอบ': 'kà-nǒm grùp-grɔ̀ɔp',
  'เครื่องดื่ม': 'krʉ̂ang-dʉ̀ʉm',
  'อาหารเช้าสไตล์กรุงเทพฯ': 'aa-hǎan-cháao sà-dtai grung-têep',
  'คนกรุงเทพฯ กินเช้าแบบเร็วๆ ของร้อน ของนม และของอบ': 'kon grung-têep gin cháao bàep reo-reo kɔ̌ɔng-rɔ́ɔn kɔ̌ɔng nom láe kɔ̌ɔng òp',
  'ของร้อนๆ (ซาลาเปา หมูปิ้ง ข้าวกล่อง)': 'kɔ̌ɔng rɔ́ɔn-rɔ́ɔn (saa-laa-bpao mǔu-bpîng kâao-glɔ̀ng)',
  'นม กาแฟ หรือชา': 'nom gaa-fɛɛ rʉ̌ʉ chaa',
  'ขนมปังหรือแซนวิช': 'kà-nǒm-bpang rʉ̌ʉ sɛɛn-wít',
  'ของฝากกลับบ้าน': 'kɔ̌ɔng-fàak glàp bâan',
  'นักท่องเที่ยวชอบของไทยๆ ที่เซเว่น ช้อปของเด็ดกลับบ้านกัน': 'nák-tɔ̂ng-tîiao chɔ̂ɔp kɔ̌ɔng tai-tai tîi sé-wên chɔ́ɔp kɔ̌ɔng-dèt glàp bâan gan',
  'สาหร่ายทอดกรอบ': 'sǎa-ràai tɔ̂ɔt grɔ̀ɔp',
  'ยาดมหรือยาหม่อง': 'yaa-dom rʉ̌ʉ yaa-mɔ̀ɔng',
  'ขนมรสไทยๆ': 'kà-nǒm rót tai-tai',
  'เครื่องดื่มไทยๆ': 'krʉ̂ang-dʉ̀ʉm tai-tai',
  'คลายร้อนกลางเมือง': 'klaai-rɔ́ɔn glaang mʉʉang',
  'กรุงเทพฯ ร้อน 35 องศา ต้องคลายร้อนให้สุด': 'grung-têep rɔ́ɔn 35 ong-sǎa dtɔ̂ng klaai-rɔ́ɔn hâi sùt',
  'น้ำเย็นๆ หรือเกลือแร่': 'nám yen-yen rʉ̌ʉ glʉʉa-rɛ̂ɛ',
  'ไอศกรีม': 'ai-sà-griim',
  'ผลไม้หรือน้ำผลไม้': 'pǒn-lá-máai rʉ̌ʉ nám-pǒn-lá-máai',
  'มื้อกลางวัน อุ่นให้ร้อน': 'mʉ́ʉ glaang-wan ùn hâi rɔ́ɔn',
  'ข้าวกล่อง เครื่องดื่ม ของหวาน และตอบรับเมื่อแคชเชียร์ถามว่า “อุ่นไหมคะ?”': 'kâao-glɔ̀ng krʉ̂ang-dʉ̀ʉm kɔ̌ɔng-wǎan láe dtɔ̀ɔp-ráp mʉ̂a káet-chîia tǎam wâa “ùn mǎi ká?”',
  'ของหวาน': 'kɔ̌ɔng-wǎan',
  'เดินเข้าอีเลฟเว่น เซเว่น กลางกรุงเทพฯ แล้วสำรวจทุกชั้นวางสินค้า': 'dəən-kâo ii-lép-wên sé-wên glaang grung-têep láeo sǎm-rùuat túk chán waang sǐn-káa',
  'นักสำรวจร้านสะดวกซื้อ': 'nák-sǎm-rùuat ráan sà-dùak-sʉ́ʉ',
  'ประเทศไทยมีร้านสะดวกซื้อมากกว่า 14,000 แห่ง คนกรุงเทพฯ ครึ่งเมืองใช้เป็นครัวที่สอง': 'bprà-têet-tai mii ráan sà-dùak-sʉ́ʉ mâak-gwàa 14,000 hɛ̀ng kon grung-têep krʉ̂ng mʉang chái bpen krua tîi sɔ̌ɔng',
  'แอร์เย็นฉ่ำของอีเลฟเว่น เซเว่น เป็นที่หลบร้อนยอดนิยมของคนกรุงเทพฯ': 'ɛɛ yen-chàm kɔ̌ɔng ii-lép-wên sé-wên bpen tîi lòp-rɔ́ɔn yɔ̂ɔt-ní-yom kɔ̌ɔng kon grung-têep',
  'นักท่องเที่ยวชอบของไทยๆ ที่อีเลฟเว่น เซเว่น ช้อปของเด็ดกลับบ้านกัน': 'nák-tɔ̂ng-tîao chɔ̂ɔp kɔ̌ɔng tai-tai tîi ii-lép-wên sé-wên chɔ́ɔp kɔ̌ɔng dèt glàp bâan gan',
  'เสียงพูดของตัวละคร (ขึ้นกับเบราว์เซอร์)': 'sǐang pûut kɔ̌ɔng dtua-lá-kɔɔn (kʉ̂n gàp brao-sə̂ə)',
  'รีเซ็ตสมุดขนม ภารกิจ และกระเป๋าเงิน?': 'rii-sét sà-mùt kà-nǒm, paa-rá-gìt, lɛ́ grà-bpǎo-ngən',
  'พบสินค้าใหม่ในสมุดขนม!': 'póp sǐn-káa mài nai sà-mùt kà-nǒm',
  'สมุดขนมครบเซ็ต': 'sà-mùt kà-nǒm króp sét',
  'ภาษา (L)': 'paa-sǎa (L)',
  'เปิด/ปิดเสียง (M)': 'bpə̀ət / bpìt sǐang (M)',
  'เปิด/ปิดเพลง (N)': 'bpə̀ət / bpìt phleeng (N)',
  'เพลงถัดไป (.)': 'phleeng tàt-bpai (.)',
  'เมนู (Esc)': 'me-nuu (Esc)',
  'สมุดขนม (B)': 'sà-mùt kà-nǒm (B)',
  'เลือกเพลง': 'lʉ̂ak phleeng',
  'เพลง': 'phleeng',
  'ปิดเสียงทั้งหมด': 'bpìt sǐang tháng-mòt',
  'เคล็ดลับ: กด H เพื่อซ่อนแถบคำแนะนำ': 'klét-láp: gòt H pʉ̂a sɔ̂n tɛ̀ɛp kam-nɛ́-nam',
};
