// UI dictionary. Every key has { en, th }.  {placeholders} are filled by t(key, vars).
export const STR = {
  // ---------------------------------------------------------------- title screen
  'title.tagline': { en: 'Step into your favourite store in Bangkok and explore every shelf.', th: 'ก้าวเข้าร้านโปรดของคุณในกรุงเทพฯ แล้วสำรวจทุกชั้นวางสินค้า', rom: 'gâao khâo ráan bpròot khɔ̌ɔng khun nai grung-thêep lɛ́ɛo sǎm-rùat túk chán waang sǐn-kháa' },
  'title.start': { en: 'Walk in', th: 'เดินเข้าร้าน' },
  'title.loading': { en: 'Stocking the shelves…', th: 'กำลังจัดสินค้าขึ้นชั้น…' },
  'title.ready': { en: 'Ready!', th: 'พร้อมแล้ว!' },
  'title.settings': { en: 'Settings', th: 'ตั้งค่า' },
  'title.controls': { en: 'Controls', th: 'ปุ่มควบคุม' },
  'title.about': { en: 'About', th: 'เกี่ยวกับเกม' },
  'title.language': { en: 'Language', th: 'ภาษา' },
  'title.hint': { en: 'Best with headphones and fullscreen. Press L in the store for mouse look.', th: 'แนะนำให้ใส่หูฟังและเล่นแบบเต็มจอ กด L ในร้านเพื่อมองด้วยเมาส์', rom: 'nɛ́-nam hâi sài hǔu-fang lɛ́ lên bɛ̀ɛp tem jɔɔ, gòt L nai ráan phʉ̂a mɔɔng dûai máo' },
  'title.flipHint': { en: 'Everything — signs, packaging, price tags — switches language.', th: 'ทั้งป้าย บรรจุภัณฑ์ และป้ายราคา จะเปลี่ยนภาษาตาม' },
  'title.install': { en: 'Play offline: tap Share, then Add to Home Screen.', th: 'เล่นแบบออฟไลน์: แตะปุ่มแชร์ แล้วเลือก "เพิ่มไปยังหน้าจอโฮม"', rom: 'lên bɛ̀ɛp ɔ́ɔf-laai: dtɛ̀ɛ bpùm chɛɛ lɛ́ɛo lûak "phə̂əm bpai yang nâa-jɔɔ hoom"' },
  'title.resume': { en: 'Continue', th: 'เล่นต่อ' },
  'lang.en': { en: 'English', th: 'English' },
  'lang.th': { en: 'ไทย', th: 'ไทย' },
  'lang.both': { en: 'EN + ไทย', th: 'EN + ไทย' },

  // ---------------------------------------------------------------- pause menu
  'menu.paused': { en: 'Paused', th: 'หยุดชั่วคราว' },
  'menu.resume': { en: 'Resume', th: 'เล่นต่อ' },
  'menu.settings': { en: 'Settings', th: 'ตั้งค่า' },
  'menu.codex': { en: 'Snack Book', th: 'สมุดขนม', rom: 'sà-mùt kà-nǒm' },
  'menu.quests': { en: 'Shopping list', th: 'รายการซื้อของ' },
  'menu.controls': { en: 'Controls', th: 'ปุ่มควบคุม' },
  'menu.title': { en: 'Main menu', th: 'กลับหน้าหลัก' },
  'menu.back': { en: 'Back', th: 'กลับ' },
  'menu.close': { en: 'Close', th: 'ปิด' },
  'menu.clickToPlay': { en: 'Click to continue', th: 'คลิกเพื่อเล่นต่อ' },

  // ---------------------------------------------------------------- settings
  'set.language': { en: 'Language', th: 'ภาษา' },
  'set.languageHelp': { en: 'Switches every sign, package, price tag and menu.', th: 'เปลี่ยนภาษาของป้าย บรรจุภัณฑ์ ป้ายราคา และเมนูทั้งหมด' },
  'set.time': { en: 'Time of day', th: 'ช่วงเวลา' },
  'set.clock': { en: 'Let the clock run', th: 'ให้เวลาเดินต่อ' },
  'set.quality': { en: 'Graphics quality', th: 'คุณภาพกราฟิก' },
  'set.q.low': { en: 'Low', th: 'ต่ำ' },
  'set.q.med': { en: 'Medium', th: 'กลาง' },
  'set.q.high': { en: 'High', th: 'สูง' },
  'set.fov': { en: 'Field of view', th: 'มุมมอง (FOV)' },
  'set.sens': { en: 'Mouse sensitivity', th: 'ความไวเมาส์' },
  'set.invert': { en: 'Invert vertical look', th: 'กลับทิศแกนแนวตั้ง' },
  'set.bob': { en: 'Head bob', th: 'กล้องโยกตามการเดิน' },
  'set.master': { en: 'Master volume', th: 'ระดับเสียงรวม' },
  'set.ambience': { en: 'Street & store ambience', th: 'เสียงบรรยากาศ' },
  'set.music': { en: 'In-store music', th: 'เพลงในร้าน' },
  'set.sfx': { en: 'Sound effects', th: 'เสียงเอฟเฟกต์' },
  'set.subtitles': { en: 'Subtitles', th: 'คำบรรยาย' },
  'set.voice': { en: 'Character voices (spoken by your browser)', th: 'เสียงพูดของตัวละคร (ขึ้นกับเบราว์เซอร์)' },
  'set.hints': { en: 'Show key hints', th: 'แสดงคำแนะนำปุ่ม' },
  'set.romanize': { en: 'Show Thai pronunciation', th: 'แสดงคำอ่านภาษาไทย' },
  'set.reset': { en: 'Reset progress', th: 'รีเซ็ตความคืบหน้า' },
  'set.resetConfirm': { en: 'Reset Snack Book, quests and wallet?', th: 'รีเซ็ตสมุดขนม ภารกิจ และกระเป๋าเงิน?' },
  'set.time.morning': { en: 'Morning 07:30', th: 'เช้า 07:30' },
  'set.time.noon': { en: 'Midday 12:30', th: 'เที่ยง 12:30' },
  'set.time.afternoon': { en: 'Afternoon 15:30', th: 'บ่าย 15:30' },
  'set.time.evening': { en: 'Evening 18:30', th: 'เย็น 18:30' },
  'set.time.night': { en: 'Night 21:30', th: 'กลางคืน 21:30' },
  'set.time.late': { en: 'Late night 02:00', th: 'ดึก 02:00' },

  // ---------------------------------------------------------------- controls legend
  'ctl.move': { en: 'Move', th: 'เดิน' },
  'ctl.look': { en: 'Look around (click and drag)', th: 'มองรอบตัว (คลิกค้างแล้วลาก)', rom: 'mɔɔng rɔ̂ɔp tua (khlík kháang lɛ́ɛo lâak)' },
  'ctl.sprint': { en: 'Sprint', th: 'วิ่ง' },
  'ctl.crouch': { en: 'Crouch (reach low shelves)', th: 'ย่อตัว (ดูชั้นล่าง)' },
  'ctl.zoom': { en: 'Zoom in to read labels (hold right-click and drag to aim slowly)', th: 'ซูมอ่านฉลาก (กดคลิกขวาค้างแล้วลากเพื่อเล็งช้าๆ)', rom: 'suum àan chà-làak (gòt khlík khwǎa kháang lɛ́ɛo lâak phʉ̂a leng cháa-cháa)' },
  'ctl.take': { en: 'Take / talk / use', th: 'หยิบ / คุย / ใช้งาน', rom: 'yìp / kui / chái-ngaan' },
  'ctl.inspect': { en: 'Inspect closely', th: 'ดูใกล้ๆ' },
  'ctl.putback': { en: 'Put back last item', th: 'วางสินค้าคืน' },
  'ctl.flip': { en: 'Flip pack front / back (inspecting)', th: 'พลิกหน้า/หลังซอง (ตอนดูใกล้ๆ)' },
  'ctl.lang': { en: 'Switch language', th: 'สลับภาษา' },
  'ctl.basket': { en: 'Basket', th: 'ตะกร้า' },
  'ctl.quests': { en: 'Shopping list', th: 'รายการซื้อของ' },
  'ctl.menu': { en: 'Pause / menu', th: 'หยุด / เมนู' },
  'ctl.hints': { en: 'Toggle hints', th: 'เปิด/ปิดคำแนะนำ' },

  // ---------------------------------------------------------------- HUD
  'hud.take': { en: 'Take', th: 'หยิบ' },
  'hud.takeTalk': { en: 'Take / talk', th: 'หยิบ / คุย', rom: 'yìp / kui' },
  'hud.inspect': { en: 'Inspect', th: 'ดูใกล้ๆ' },
  'hud.putback': { en: 'Put back', th: 'วางคืน' },
  'hud.use': { en: 'Use', th: 'ใช้งาน' },
  'hud.open': { en: 'Open', th: 'เปิด' },
  'hud.close': { en: 'Close', th: 'ปิด' },
  'hud.talk': { en: 'Talk', th: 'คุยด้วย' },
  'hud.cash': { en: 'Cash', th: 'เงินสด' },
  'hud.bank': { en: 'Bank', th: 'บัญชี' },
  'hud.basket': { en: 'Basket', th: 'ตะกร้า' },
  'hud.hands': { en: 'Hands', th: 'ในมือ' },
  'hud.codex': { en: 'Snack Book', th: 'สมุดขนม', rom: 'sà-mùt kà-nǒm' },
  'hud.outside': { en: 'Outside', th: 'ข้างนอก' },
  'hud.inside': { en: 'Inside', th: 'ในร้าน' },
  'hud.handsFull': { en: 'Hands full! Grab a basket by the door.', th: 'มือเต็มแล้ว! หยิบตะกร้าตรงประตูก่อนนะ' },
  'hud.basketFull': { en: 'The basket is full.', th: 'ตะกร้าเต็มแล้ว' },
  'hud.grabBasket': { en: 'Take a basket', th: 'หยิบตะกร้า' },
  'hud.dropBasket': { en: 'Put the basket back', th: 'วางตะกร้าคืน' },
  'hud.gotBasket': { en: 'You picked up a basket.', th: 'หยิบตะกร้าแล้ว' },
  'hud.added': { en: 'Added: {name}', th: 'หยิบแล้ว: {name}' },
  'hud.removed': { en: 'Put back: {name}', th: 'วางคืนแล้ว: {name}' },
  'hud.nothingToPutBack': { en: 'Nothing to put back.', th: 'ไม่มีสินค้าให้วางคืน' },
  'hud.newDiscovery': { en: 'New in your Snack Book!', th: 'พบสินค้าใหม่ในสมุดขนม!' },
  'hud.alcoholClosed': { en: 'Alcohol can’t be sold right now (Thai law: 11:00–14:00 and 17:00–24:00 only).', th: 'ตอนนี้ขายเครื่องดื่มแอลกอฮอล์ไม่ได้ (กฎหมายไทย: 11.00–14.00 น. และ 17.00–24.00 น. เท่านั้น)' },
  'hud.tobacco': { en: 'Tobacco is kept out of sight in Thailand — ask the cashier (must be 20+).', th: 'บุหรี่ต้องเก็บมิดชิดตามกฎหมายไทย ต้องสอบถามพนักงาน (อายุ 20 ปีขึ้นไป)' },
  'hud.scanQr': { en: 'Scan', th: 'สแกน' },
  'hud.language': { en: 'Language', th: 'ภาษา' },
  'hud.kcal': { en: 'kcal', th: 'กิโลแคลอรี' },
  'hud.temp': { en: 'Outside {t}°C · Inside {i}°C', th: 'ข้างนอก {t}°C · ในร้าน {i}°C' },
  'hud.zone': { en: 'Entering', th: 'เข้าสู่' },
  'hud.price': { en: 'Price', th: 'ราคา' },
  'hud.total': { en: 'Total', th: 'รวม' },
  'hud.items': { en: '{n} items', th: '{n} ชิ้น' },
  'hud.item1': { en: '1 item', th: '1 ชิ้น' },
  'hud.hint.move': { en: 'WASD move · Shift sprint · C crouch · Z zoom', th: 'WASD เดิน · Shift วิ่ง · C ย่อ · Z ซูม' },
  'hud.hint.act': { en: 'E take · F inspect · G put back · L language', th: 'E หยิบ · F ดูใกล้ๆ · G วางคืน · L สลับภาษา' },
  'hud.hint.ui': { en: 'B basket · P codex · Q list · Esc menu', th: 'B ตะกร้า · P สมุดสะสม · Q รายการ · Esc เมนู' },
  'hud.hint.enter': { en: 'Walk to the glass doors — they open automatically.', th: 'เดินไปที่ประตูกระจก ประตูจะเปิดเองอัตโนมัติ' },

  // ---------------------------------------------------------------- inspect / product card
  'card.brand': { en: 'Brand', th: 'ยี่ห้อ' },
  'card.size': { en: 'Net contents', th: 'ปริมาณสุทธิ' },
  'card.ingredients': { en: 'Ingredients', th: 'ส่วนประกอบ' },
  'card.allergens': { en: 'Contains', th: 'มีส่วนผสมของ' },
  'card.about': { en: 'About', th: 'เกร็ดน่ารู้' },
  'card.where': { en: 'Found in', th: 'วางอยู่ที่' },
  'card.category': { en: 'Category', th: 'หมวดสินค้า' },
  'card.flip': { en: 'Flip', th: 'พลิก' },
  'card.rotate': { en: 'Move mouse to rotate', th: 'ขยับเมาส์เพื่อหมุน' },
  'card.leave': { en: 'Put it down', th: 'วางลง' },
  'card.heat': { en: 'Heat in microwave', th: 'อุ่นไมโครเวฟได้' },
  'card.alcohol': { en: 'Alcohol · 20+ only', th: 'แอลกอฮอล์ · 20 ปีขึ้นไป' },
  'card.front': { en: 'Front', th: 'ด้านหน้า' },
  'card.back': { en: 'Back', th: 'ด้านหลัง' },
  'card.eaten': { en: 'Yum!', th: 'อร่อย!' },

  // ---------------------------------------------------------------- codex
  'codex.title': { en: 'Snack Book', th: 'สมุดขนม', rom: 'sà-mùt kà-nǒm' },
  'codex.sub': { en: 'Inspect things (I) to add them to your Snack Book.', th: 'ดูสินค้าใกล้ๆ (กด I) เพื่อบันทึกลงสมุด', rom: 'duu sǐn-kháa glâi-glâi (gòt I) phʉ̂a ban-tʉ́k long sà-mùt' },
  'codex.found': { en: '{a} / {b} discovered', th: 'พบแล้ว {a} / {b}' },
  'codex.all': { en: 'All', th: 'ทั้งหมด' },
  'codex.unknown': { en: '???', th: '???' },
  'codex.undiscovered': { en: 'Not discovered yet — keep exploring!', th: 'ยังไม่พบ — สำรวจต่อไป!' },
  'codex.search': { en: 'Search products…', th: 'ค้นหาสินค้า…' },
  'codex.reveal': { en: 'Reveal all', th: 'แสดงทั้งหมด' },
  'codex.foundOnly': { en: 'Discovered only', th: 'เฉพาะที่พบแล้ว', rom: 'chà-phɔ́ thîi phóp lɛ́ɛo' },
  'codex.noneFound': { en: 'Nothing here yet. Press I on a product to inspect it and add it to your Snack Book.', th: 'ยังไม่มีสินค้า กด I ที่สินค้าเพื่อดูใกล้ๆ และบันทึกลงสมุด', rom: 'yang mâi mii sǐn-kháa gòt I thîi sǐn-kháa phʉ̂a duu glâi-glâi lɛ́ ban-tʉ́k long sà-mùt' },
  'codex.hide': { en: 'Hide undiscovered', th: 'ซ่อนที่ยังไม่พบ' },

  // ---------------------------------------------------------------- quests
  'quest.title': { en: 'Shopping list', th: 'รายการซื้อของ' },
  'quest.pick': { en: 'Choose a mission', th: 'เลือกภารกิจ' },
  'quest.active': { en: 'Active mission', th: 'ภารกิจปัจจุบัน' },
  'quest.done': { en: 'Mission complete!', th: 'ภารกิจสำเร็จ!' },
  'quest.reward': { en: 'Reward: +{n} 11 Club points', th: 'รางวัล: +{n} แต้ม 11 Club' },
  'quest.abandon': { en: 'Drop mission', th: 'ยกเลิกภารกิจ' },
  'quest.start': { en: 'Start', th: 'เริ่ม' },
  'quest.none': { en: 'No active mission. Open the list (Q) to pick one.', th: 'ยังไม่มีภารกิจ กด Q เพื่อเลือก' },
  'quest.buy': { en: 'Buy', th: 'ซื้อ' },
  'quest.any': { en: 'any', th: 'อะไรก็ได้' },

  // ---------------------------------------------------------------- basket
  'basket.title': { en: 'Your basket', th: 'ตะกร้าของคุณ' },
  'hands.title': { en: 'In your hands', th: 'ของในมือคุณ', rom: 'kɔ̌ɔng nai mʉʉ kun' },
  'basket.empty': { en: 'Empty. Go browse the shelves!', th: 'ยังว่างอยู่ ไปเดินดูสินค้ากันเถอะ!' },
  'basket.putBack': { en: 'Put back', th: 'วางคืน' },
  'basket.tip': { en: 'Tip: your hands hold {h} items. Grab a basket by the door to carry up to {b}.', th: 'เคล็ดลับ: มือถือของได้ {h} ชิ้น หยิบตะกร้าตรงประตูเพื่อใส่ได้ถึง {b} ชิ้น', rom: 'khlét-láp: mʉʉ thʉ̌ʉ kɔ̌ɔng dâi {h} chín, yìp dtà-grâa dtrong bprà-dtuu phʉ̂a sài dâi thʉ̌ng {b} chín' },
  'basket.inspect': { en: 'Inspect', th: 'ดูสินค้า', rom: 'duu sǐn-kháa' },
  'card.done': { en: 'Done', th: 'เสร็จแล้ว', rom: 'sèt lɛ́ɛo' },
  'basket.subtotal': { en: 'Subtotal', th: 'รวมเป็นเงิน' },
  'basket.toCounter': { en: 'Take it to the cashier counter to pay.', th: 'นำไปชำระเงินที่เคาน์เตอร์แคชเชียร์' },
  'basket.bought': { en: 'Purchased items', th: 'สินค้าที่ซื้อแล้ว' },
  'basket.consume': { en: 'Enjoy', th: 'ทาน/ใช้' },

  // ---------------------------------------------------------------- checkout
  'co.title': { en: 'Cashier', th: 'แคชเชียร์' },
  'co.greet': { en: 'Start checkout', th: 'ชำระเงิน' },
  'co.emptyBasket': { en: 'Your basket is empty.', th: 'ตะกร้าของคุณยังว่างอยู่' },
  'co.yes': { en: 'Yes', th: 'ค่ะ/ครับ' },
  'co.no': { en: 'No', th: 'ไม่ต้อง' },
  'co.heatYes': { en: 'Yes, heat it', th: 'อุ่นด้วย' },
  'co.heatNo': { en: 'No thanks', th: 'ไม่ต้องอุ่น' },
  'co.bagYes': { en: 'Yes, a bag please', th: 'ขอถุงด้วย' },
  'co.bagNo': { en: 'No bag', th: 'ไม่รับถุง' },
  'co.cutlery': { en: 'Yes please', th: 'ขอด้วย' },
  'co.memberYes': { en: 'Yes (scan app)', th: 'มี (สแกนแอป)' },
  'co.memberNo': { en: 'No', th: 'ไม่มี' },
  'co.howPay': { en: 'How would you like to pay?', th: 'ชำระเงินด้วยวิธีไหน?' },
  'co.cash': { en: 'Cash', th: 'เงินสด' },
  'co.promptpay': { en: 'PromptPay QR', th: 'พร้อมเพย์ (QR)' },
  'co.truemoney': { en: 'TrueMoney Wallet', th: 'ทรูมันนี่ วอลเล็ท' },
  'co.notEnough': { en: 'Not enough money for this payment method.', th: 'เงินไม่พอสำหรับวิธีชำระนี้' },
  'co.scanNow': { en: 'Scan the QR code with your banking app', th: 'สแกน QR ด้วยแอปธนาคารของคุณ' },
  'co.scanBtn': { en: 'Scan & pay', th: 'สแกนเพื่อจ่าย' },
  'co.paid': { en: 'Payment complete', th: 'ชำระเงินเรียบร้อย' },
  'co.change': { en: 'Change', th: 'เงินทอน' },
  'co.given': { en: 'Cash given', th: 'รับเงินมา' },
  'co.total': { en: 'Total', th: 'ยอดรวม' },
  'co.cancel': { en: 'Cancel', th: 'ยกเลิก' },
  'co.receipt': { en: 'Receipt', th: 'ใบเสร็จ' },
  'co.saveReceipt': { en: 'Save receipt as image', th: 'บันทึกใบเสร็จเป็นรูป' },
  'co.continue': { en: 'Continue shopping', th: 'เดินต่อ' },
  'co.points': { en: '+{n} 11 Club points', th: '+{n} แต้ม 11 Club' },
  'co.eco': { en: 'Eco bonus for skipping the bag!', th: 'โบนัสรักษ์โลกที่ไม่รับถุง!' },
  'co.showId': { en: 'Show ID card', th: 'ยื่นบัตรประชาชน' },
  'co.payNow': { en: 'Pay ฿{n}', th: 'ชำระ ฿{n}' },
  'co.ageCheck': { en: 'The cashier asks for ID for age-restricted items.', th: 'พนักงานขอตรวจบัตรประชาชนสำหรับสินค้าที่จำกัดอายุ' },

  // ---------------------------------------------------------------- receipt
  'rc.company': { en: 'CP ALL Public Company Limited', th: 'บริษัท ซีพี ออลล์ จำกัด (มหาชน)' },
  'rc.branch': { en: 'Branch 07711: Sukhumvit 11', th: 'สาขา 07711 สุขุมวิท 11', rom: 'sǎa-khǎa 07711 sù-khǔm-wít 11' },
  'rc.address': { en: 'Soi Sukhumvit 11, Khlong Toei Nuea, Watthana, Bangkok 10110', th: 'ซอยสุขุมวิท 11 แขวงคลองเตยเหนือ เขตวัฒนา กรุงเทพฯ 10110', rom: 'sɔɔi sù-khǔm-wít 11, khwɛ̌ɛng khlɔɔng-dtəəi nʉ̌a, khèet wát-thá-naa, grung-thêep 10110' },
  'rc.taxInvoice': { en: 'RECEIPT / ABBREVIATED TAX INVOICE', th: 'ใบเสร็จรับเงิน/ใบกำกับภาษีอย่างย่อ' },
  'rc.taxId': { en: 'TAX ID', th: 'เลขประจำตัวผู้เสียภาษี' },
  'rc.qty': { en: 'Qty', th: 'จำนวน' },
  'rc.item': { en: 'Item', th: 'รายการ' },
  'rc.amount': { en: 'Amount', th: 'จำนวนเงิน' },
  'rc.subtotal': { en: 'Subtotal', th: 'รวมเงิน' },
  'rc.vat': { en: 'VAT 7% (incl.)', th: 'ภาษีมูลค่าเพิ่ม 7% (รวมแล้ว)' },
  'rc.total': { en: 'TOTAL', th: 'ยอดสุทธิ' },
  'rc.cash': { en: 'Cash', th: 'เงินสด' },
  'rc.change': { en: 'Change', th: 'เงินทอน' },
  'rc.pp': { en: 'PromptPay', th: 'พร้อมเพย์' },
  'rc.tm': { en: 'TrueMoney', th: 'ทรูมันนี่' },
  'rc.points': { en: '11 Club points earned', th: 'แต้ม 11 Club ที่ได้รับ' },
  'rc.thanks': { en: 'Thank you — see you again!', th: 'ขอบคุณที่ใช้บริการ' },
  'rc.tagline': { en: 'Always open, always close to you.', th: 'สะดวกทุกที่ ทุกเวลา' },
  'rc.cashier': { en: 'Cashier', th: 'พนักงาน' },
  'rc.pos': { en: 'POS', th: 'เครื่อง POS' },
  'rc.heated': { en: 'heated', th: 'อุ่นแล้ว' },

  // ---------------------------------------------------------------- misc / achievements
  'ach.unlocked': { en: 'Achievement unlocked', th: 'ปลดล็อกความสำเร็จ' },
  'ach.first': { en: 'Sawasdee!', th: 'สวัสดี!' },
  'ach.firstDesc': { en: 'Walk into the store for the first time.', th: 'เดินเข้าร้านเป็นครั้งแรก' },
  'ach.bilingual': { en: 'Bilingual', th: 'สองภาษา' },
  'ach.bilingualDesc': { en: 'Flip the language while reading a package.', th: 'สลับภาษาระหว่างอ่านซองสินค้า' },
  'ach.shopper': { en: 'Basket Case', th: 'ตะกร้าเต็ม' },
  'ach.shopperDesc': { en: 'Put 10 items in your basket.', th: 'ใส่สินค้า 10 ชิ้นในตะกร้า' },
  'ach.explorer': { en: 'Curious Shopper', th: 'นักสำรวจร้านสะดวกซื้อ' },
  'ach.explorerDesc': { en: 'Discover 25 products.', th: 'พบสินค้า 25 ชนิด' },
  'ach.collector': { en: 'Full Snack Book', th: 'สมุดขนมครบเซ็ต' },
  'ach.collectorDesc': { en: 'Discover every product in the store.', th: 'พบสินค้าครบทุกชนิดในร้าน' },
  'ach.heater': { en: 'Ting!', th: 'ติ๊ง!' },
  'ach.heaterDesc': { en: 'Have a meal heated in the microwave.', th: 'ให้พนักงานอุ่นอาหารในไมโครเวฟ' },
  'ach.promptpay': { en: 'Scan to Pay', th: 'สแกนจ่าย' },
  'ach.promptpayDesc': { en: 'Pay with a PromptPay QR code.', th: 'จ่ายเงินด้วย QR พร้อมเพย์' },
  'ach.dog': { en: 'Soi Dog Whisperer', th: 'เพื่อนสี่ขาหน้าร้าน' },
  'ach.dogDesc': { en: 'Say hello to the sleepy dog outside.', th: 'ทักทายน้องหมาขี้เซาหน้าร้าน' },
  'ach.eco': { en: 'Green Shopper', th: 'นักช้อปรักษ์โลก' },
  'ach.ecoDesc': { en: 'Skip the bag at checkout.', th: 'ไม่รับถุงตอนชำระเงิน' },
  'ach.atm': { en: 'Cash Machine', th: 'ตู้เอทีเอ็ม' },
  'ach.atmDesc': { en: 'Withdraw cash from the ATM.', th: 'ถอนเงินจากตู้เอทีเอ็ม' },
  'ach.night': { en: 'Midnight Run', th: 'ซื้อของดึก' },
  'ach.nightDesc': { en: 'Buy something between midnight and 5 AM.', th: 'ซื้อของช่วงเที่ยงคืนถึงตีห้า' },
  'ach.quest': { en: 'Mission Accomplished', th: 'ภารกิจสำเร็จ' },
  'ach.questDesc': { en: 'Complete a shopping mission.', th: 'ทำภารกิจซื้อของสำเร็จ' },

  'atm.title': { en: 'ATM', th: 'ตู้เอทีเอ็ม' },
  'atm.prompt': { en: 'Withdraw ฿500', th: 'ถอนเงิน ฿500' },
  'atm.done': { en: 'Withdrew ฿500 — cash added.', th: 'ถอนเงิน ฿500 แล้ว' },
  'atm.fee': { en: 'No fee on this card today.', th: 'วันนี้ไม่มีค่าธรรมเนียม' },
  'atm.limit': { en: 'The ATM is out of cash for you today.', th: 'วันนี้ถอนเต็มวงเงินแล้ว' },

  'zone.outside': { en: 'Sukhumvit Soi 11', th: 'ซอยสุขุมวิท 11', rom: 'sɔɔi sù-khǔm-wít sìp-èt' },
  'zone.outsideSub': { en: 'Bangkok, Thailand', th: 'กรุงเทพฯ ประเทศไทย', rom: 'grung-thêep, bprà-thêet thai' },
  'zone.entrance': { en: 'Entrance', th: 'ทางเข้า' },
  'zone.counter': { en: 'Cashier Counter', th: 'เคาน์เตอร์แคชเชียร์' },
  'zone.noodles': { en: 'Instant Noodles', th: 'บะหมี่กึ่งสำเร็จรูป' },
  'zone.snacks': { en: 'Snacks', th: 'ขนมขบเคี้ยว' },
  'zone.sweets': { en: 'Sweets & Biscuits', th: 'ขนมหวานและบิสกิต' },
  'zone.household': { en: 'Household & Personal Care', th: 'ของใช้ในบ้านและของใช้ส่วนตัว' },
  'zone.health': { en: 'Health & Remedies', th: 'ยาสามัญและสมุนไพร' },
  'zone.meals': { en: 'Ready Meals', th: 'อาหารพร้อมทาน' },
  'zone.drinks': { en: 'Drinks Coolers', th: 'ตู้แช่เครื่องดื่ม' },
  'zone.beer': { en: 'Beer & Spirits', th: 'เบียร์และสุรา' },
  'zone.icecream': { en: 'Ice Cream Freezer', th: 'ตู้แช่ไอศกรีม' },
  'zone.hotwater': { en: 'Hot Water & Microwave', th: 'น้ำร้อนและไมโครเวฟ' },
  'zone.atm': { en: 'ATM & Services', th: 'ตู้เอทีเอ็มและบริการ' },
  'zone.bakery': { en: 'Bakery', th: 'เบเกอรี่' },
  'zone.seating': { en: 'Window Bar', th: 'เคาน์เตอร์นั่งทาน' },
  'zone.grocery': { en: 'Pantry', th: 'ของแห้งและเครื่องปรุง' },
  'zone.hot': { en: 'Hot Foods & 11 Café', th: 'อาหารร้อนและอีเลฟเว่น คาเฟ่' },

  'toast.reset': { en: 'Progress reset.', th: 'รีเซ็ตความคืบหน้าแล้ว' },
  'toast.saved': { en: 'Receipt saved.', th: 'บันทึกใบเสร็จแล้ว' },
  'toast.langOn': { en: 'Language: English', th: 'ภาษา: อังกฤษ' },
  'toast.langTh': { en: 'Language: Thai', th: 'ภาษา: ไทย' },
  'toast.langBoth': { en: 'Language: English + Thai', th: 'ภาษา: อังกฤษ + ไทย' },
  'toast.dog': { en: 'The soi dog opens one eye… and goes back to sleep.', th: 'น้องหมาลืมตาข้างหนึ่ง แล้วก็หลับต่อ' },
  'toast.microwave': { en: 'Ting! Your meal is hot.', th: 'ติ๊ง! อาหารร้อนแล้ว' },
  'toast.fullscreen': { en: 'Press F11 for fullscreen', th: 'กด F11 เพื่อเล่นเต็มจอ' },
  'toast.noWallet': { en: 'Not enough cash — find the ATM!', th: 'เงินไม่พอ — ไปหาตู้เอทีเอ็ม!' },
  // ---------------------------------------------------------------- settings sections & about
  'set.sec.lang': { en: 'Language & world', th: 'ภาษาและโลกในเกม' },
  'set.sec.gfx': { en: 'Graphics', th: 'กราฟิก' },
  'set.sec.ctl': { en: 'Controls', th: 'การควบคุม' },
  'set.sec.snd': { en: 'Sound', th: 'เสียง' },
  'set.sec.play': { en: 'Gameplay & accessibility', th: 'การเล่นและการเข้าถึง' },
  'set.needReload': { en: 'Some graphics changes apply after reloading the page.', th: 'การตั้งค่ากราฟิกบางอย่างจะมีผลหลังโหลดหน้าใหม่' },
  'set.reload': { en: 'Reload now', th: 'โหลดใหม่ตอนนี้' },
  'about.p1': { en: '7 Eleven Simulator is a love letter to the corner store that never closes. Walk in from a Bangkok soi, explore every shelf, and flip the whole world between English and Thai.', th: '7 Eleven Simulator คือจดหมายรักถึงร้านสะดวกซื้อที่ไม่เคยปิด เดินเข้าร้านจากซอยกลางกรุงเทพฯ สำรวจทุกชั้นวาง และสลับโลกทั้งใบระหว่างภาษาอังกฤษกับไทยได้' },
  'about.p2': { en: 'Made by Nomaditsu with three.js. Everything — packaging, signs, sounds, even the receipts — is generated live in your browser. There are no external assets.', th: 'สร้างโดย Nomaditsu ด้วย three.js ทุกอย่าง ทั้งบรรจุภัณฑ์ ป้าย เสียง และใบเสร็จ ถูกสร้างสดในเบราว์เซอร์ของคุณ ไม่มีไฟล์ภายนอก' },
  'about.p3': { en: 'Fan-made tribute. Not affiliated with or endorsed by 7-Eleven, CP ALL or any brand shown. Product names are used descriptively; artwork is stylised. Ingredient lists, addresses and registration numbers on the packs are illustrative.', th: 'เกมนี้ทำขึ้นเพื่อความบันเทิงและเป็นการคารวะร้านสะดวกซื้อ ไม่มีส่วนเกี่ยวข้องหรือได้รับการรับรองจากเซเว่น อีเลฟเว่น ซีพี ออลล์ หรือแบรนด์ใดๆ ชื่อสินค้าใช้เพื่อการอธิบาย งานภาพเป็นสไตล์เฉพาะตัว ข้อมูลส่วนประกอบ ที่อยู่ และเลขทะเบียนบนบรรจุภัณฑ์เป็นเพียงตัวอย่าง' },
  'about.p4': { en: 'Thai phrases you will hear: สวัสดีค่ะ (hello), อุ่นไหมคะ (heat it?), รับถุงไหมคะ (a bag?), ขอบคุณค่ะ (thank you).', th: 'ประโยคที่จะได้ยินในร้าน: สวัสดีค่ะ, อุ่นไหมคะ, รับถุงไหมคะ, ขอบคุณค่ะ' },
  'about.tech': { en: 'Tip: turn on “Show Thai pronunciation” in Settings to learn how each line is said.', th: 'เคล็ดลับ: เปิด “แสดงคำอ่านภาษาไทย” ในการตั้งค่า เพื่อดูวิธีอ่านแต่ละประโยค' },
  'panel.hotwater': { en: 'Hot water for your noodles', th: 'น้ำร้อนสำหรับบะหมี่ของคุณ' },
  'interact.basket': { en: 'Basket', th: 'ตะกร้า' },
  'interact.pos': { en: 'Cashier', th: 'แคชเชียร์' },
  'interact.atm': { en: 'ATM', th: 'ตู้เอทีเอ็ม' },
  'interact.microwave': { en: 'Microwave', th: 'ไมโครเวฟ' },
  'interact.hotwater': { en: 'Hot water', th: 'น้ำร้อน' },
  'interact.coffee': { en: '11 Café machine', th: 'เครื่องอีเลฟเว่น คาเฟ่' },
  'interact.dog': { en: 'Sleepy dog', th: 'น้องหมาขี้เซา' },
  'interact.stool': { en: 'Sit down', th: 'นั่ง' },
  'act.pay': { en: 'Pay', th: 'ชำระเงิน' },
  'act.withdraw': { en: 'Withdraw ฿500', th: 'ถอนเงิน ฿500' },
  'act.heat': { en: 'Heat a meal', th: 'อุ่นอาหาร' },
  'act.pour': { en: 'Add hot water', th: 'เติมน้ำร้อน' },
  'act.order': { en: 'Order a drink', th: 'สั่งเครื่องดื่ม' },
  'act.pet': { en: 'Say hello', th: 'ทักทาย' },
  'act.take': { en: 'Take', th: 'หยิบ' },
  'mw.none': { en: 'Put a ready meal in your basket first.', th: 'ใส่อาหารพร้อมทานในตะกร้าก่อนนะ' },
  'mw.heating': { en: 'Heating…', th: 'กำลังอุ่น…' },
  'mw.already': { en: 'Everything in your basket that can be heated is already hot.', th: 'อาหารที่อุ่นได้ในตะกร้าร้อนหมดแล้ว' },
  'hw.none': { en: 'You need a cup noodle in your basket.', th: 'ต้องมีบะหมี่ถ้วยในตะกร้าก่อน' },
  'hw.done': { en: 'Hot water added — wait 3 minutes!', th: 'เติมน้ำร้อนแล้ว รอ 3 นาทีนะ!' },
  'cafe.title': { en: '11 Café — choose a drink', th: 'อีเลฟเว่น คาเฟ่ — เลือกเครื่องดื่ม' },
  'cafe.made': { en: 'Enjoy your {name}!', th: 'ขอให้อร่อยกับ{name}นะคะ!' },
  'bag.title': { en: 'Purchased items', th: 'สินค้าที่ซื้อแล้ว' },
  'bag.empty': { en: 'Nothing bought yet.', th: 'ยังไม่ได้ซื้ออะไร' },
  'bag.enjoy': { en: 'You enjoy the {name}. Delicious!', th: 'คุณทาน{name}อย่างเอร็ดอร่อย!' },
  'sit.done': { en: 'You sit at the window and watch the motorbikes go by…', th: 'คุณนั่งที่เคาน์เตอร์ริมกระจก มองมอเตอร์ไซค์ผ่านไปมา…' },
  'hud.night': { en: 'Night', th: 'กลางคืน' },
  'hud.day': { en: 'Day', th: 'กลางวัน' },
  'hud.restrictedNow': { en: 'Not on sale at this hour', th: 'ไม่จำหน่ายในเวลานี้' },
  'pause.hours': { en: 'Game time', th: 'เวลาในเกม' },

};

// Loading-screen tips.
export const TIPS = [
  { en: 'Thailand has well over 14,000 corner convenience stores. Half of Bangkok treats them like a second kitchen.', th: 'ประเทศไทยมีร้านสะดวกซื้อมากกว่า 14,000 แห่ง คนกรุงเทพฯ ครึ่งเมืองใช้เป็นครัวที่สอง' },
  { en: 'Alcohol may only be sold 11:00–14:00 and 17:00–24:00 in Thailand — the beer coolers get covered in between.', th: 'ในประเทศไทยจำหน่ายเครื่องดื่มแอลกอฮอล์ได้เฉพาะเวลา 11.00–14.00 น. และ 17.00–24.00 น. ช่วงอื่นจะมีผ้าคลุมตู้แช่' },
  { en: 'Cigarettes are hidden behind the counter — displaying tobacco at the point of sale is banned in Thailand.', th: 'บุหรี่ต้องเก็บมิดชิดหลังเคาน์เตอร์ เพราะกฎหมายไทยห้ามโชว์สินค้ายาสูบ ณ จุดขาย' },
  { en: 'Try the classic: ข้าวกะเพราไก่ไข่ดาว — spicy holy basil chicken with a fried egg, ready in the microwave.', th: 'ลองเมนูสุดฮิต ข้าวกะเพราไก่ไข่ดาว อุ่นไมโครเวฟก็อร่อยได้ทันที' },
  { en: '“อุ่นไหมคะ?” means “Shall I heat that up?” — you will hear it at every visit.', th: '“อุ่นไหมคะ?” แปลว่า “ให้อุ่นให้ไหมคะ?” เป็นประโยคที่จะได้ยินทุกครั้งที่ไปซื้อของ' },
  { en: 'Crispy seaweed (สาหร่ายทอดกรอบ) is Thailand’s favourite tourist snack to take home.', th: 'สาหร่ายทอดกรอบเป็นขนมที่นักท่องเที่ยวซื้อกลับบ้านมากที่สุดอย่างหนึ่ง' },
  { en: 'The air-conditioning is famously arctic — half of Bangkok pops in just to cool off.', th: 'แอร์เย็นฉ่ำของอีเลฟเว่น เซเว่น เป็นที่หลบร้อนยอดนิยมของคนกรุงเทพฯ' },
  { en: 'Grilled pork skewers with sticky rice (หมูปิ้งข้าวเหนียว) are the classic Bangkok breakfast in a bag.', th: 'หมูปิ้งข้าวเหนียวคืออาหารเช้ายอดฮิตของคนกรุงเทพฯ' },
  { en: 'Look for the Thai-only flavours: Nori, Tom Yum, Salted Egg, Spicy Squid, Larb…', th: 'มองหารสชาติสไตล์ไทย เช่น สาหร่ายโนริ ต้มยำ ไข่เค็ม ปลาหมึกย่าง ลาบ…' },
];

// Thai-language phrase book shown as subtitles at checkout (romanisation + meaning).
export const PHRASES = {
  // what the staff call out every time the entrance doors open (the classic Thai 7-Eleven greeting)
  doorGreet: { th: 'สวัสดีค่ะ เชิญค่ะ', rom: 'sà-wàt-dii khâ, chəən khâ', en: 'Hello, please come in!', spoken: 'Sawasdee kha. Chern kha.' },
  welcome: { th: 'สวัสดีค่ะ ยินดีต้อนรับสู่อีเลฟเว่น เซเว่น ค่ะ', rom: 'sà-wàt-dii kâ, yin-dii dtɔ̂ɔn-ráp sùu ii-lép-wên sé-wên kâ', en: 'Hello! Welcome to 11 SEVEN.' },
  member: { th: 'มีแอปอีเลฟเว่น คลับไหมคะ', rom: 'mii áep ii-lép-wên kláp mǎi ká', en: 'Do you have the 11 Club app?' },
  heat: { th: 'อุ่นไหมคะ', rom: 'ùn mǎi ká', en: 'Would you like that heated?' },
  bag: { th: 'รับถุงไหมคะ', rom: 'ráp tǔng mǎi ká', en: 'Would you like a bag?' },
  cutlery: { th: 'รับช้อนส้อมไหมคะ', rom: 'ráp chɔ́ɔn sɔ̂m mǎi ká', en: 'Would you like a spoon and fork?' },
  straw: { th: 'รับหลอดไหมคะ', rom: 'ráp lɔ̀ɔt mǎi ká', en: 'Would you like a straw?' },
  chopsticks: { th: 'รับตะเกียบไหมคะ', rom: 'ráp dtà-gìap mǎi ká', en: 'Would you like chopsticks?' },
  total: { th: 'ทั้งหมด {n} บาทค่ะ', rom: 'tháng-mòt {n} bàat kâ', en: 'That comes to {n} baht.' },
  howPay: { th: 'ชำระด้วยอะไรคะ', rom: 'cham-rá dûai à-rai ká', en: 'How would you like to pay?' },
  received: { th: 'รับเงิน {n} บาทค่ะ', rom: 'ráp ngən {n} bàat kâ', en: 'Received {n} baht.' },
  change: { th: 'ทอน {n} บาทค่ะ', rom: 'tɔɔn {n} bàat kâ', en: '{n} baht change.' },
  scan: { th: 'สแกนคิวอาร์ได้เลยค่ะ', rom: 'sà-gɛɛn kiu-aa dâai ləəi kâ', en: 'You can scan the QR code now.' },
  paid: { th: 'ชำระเงินเรียบร้อยค่ะ', rom: 'cham-rá ngən rîap-rɔ́ɔi kâ', en: 'Payment complete.' },
  thanks: { th: 'ขอบคุณค่ะ', rom: 'kɔ̀ɔp-kun kâ', en: 'Thank you!' },
  thanks2: { th: 'ขอบคุณที่ใช้บริการค่ะ', rom: 'kɔ̀ɔp-kun tîi cháai bɔɔ-rí-gaan kâ', en: 'Thank you for shopping with us.' },
  ageId: { th: 'ขอดูบัตรประชาชนด้วยนะคะ', rom: 'kɔ̌ɔ duu bàt bprà-chaa-chon dûai ná ká', en: 'May I see your ID, please?' },
  noAlcohol: { th: 'ขออภัยค่ะ ตอนนี้ขายเครื่องดื่มแอลกอฮอล์ไม่ได้ค่ะ', rom: 'kɔ̌ɔ à-pai kâ, dtɔɔn-níi kǎai krɯ̂ɯang-dɯ̀ɯm ɛɛn-gɔɔ-hɔɔ mâi dâai kâ', en: 'Sorry, we can’t sell alcohol at this time.' },
  empty: { th: 'ตะกร้ายังว่างอยู่นะคะ', rom: 'dtà-krâa yang wâang yùu ná ká', en: 'Your basket is still empty.' },
  wai: { th: 'สวัสดีค่ะ', rom: 'sà-wàt-dii kâ', en: 'Hello!' },
};
