// UI strings added by the HUD / controls / about / dialogue overhaul. Every entry is { en, th, rom? }:
// `rom` is the romanised Thai shown between the English and the Thai script in bilingual mode.
export const STR_UI = {
  // ---------------------------------------------------------------- top bar & hints
  'hud.by': { en: 'by', th: 'โดย', rom: 'dooi' },
  'hud.snackbook': { en: 'Snack Book', th: 'สมุดขนม', rom: 'sà-mùt kà-nǒm' },
  'hud.move': { en: 'Move', th: 'เดิน', rom: 'dəən' },
  'hud.sprintCrouch': { en: 'Shift sprint · C crouch', th: 'Shift วิ่ง · C ย่อตัว', rom: 'Shift wîng · C yɔ̂ɔ dtua' },
  'hud.hideHints': { en: 'Hide hints', th: 'ซ่อนคำแนะนำ', rom: 'sɔ̂n kam-nɛ́-nam' },
  'hud.showHints': { en: 'Show hints', th: 'แสดงคำแนะนำ', rom: 'sà-dɛɛng kam-nɛ́-nam' },
  'hud.talkTo': { en: 'Talk to {name}', th: 'คุยกับ {name}', rom: 'kui gàp {name}' },
  'act.talkPay': { en: 'Talk / pay', th: 'คุย / ชำระเงิน', rom: 'kui / cham-rá ngən' },
  'talk.pay': { en: 'I would like to pay', th: 'ขอชำระเงินหน่อย', rom: 'kɔ̌ɔ cham-rá ngən nɔ̀ɔi' },
  'act.talk': { en: 'Talk', th: 'คุยด้วย', rom: 'kui dûai' },
  'hud.tapToTalk': { en: 'Talk', th: 'คุย', rom: 'kui' },
  'btn.lang': { en: 'Language (L)', th: 'ภาษา (L)' },
  'btn.sound': { en: 'Sound effects on / off (N)', th: 'เปิด/ปิดเสียงเอฟเฟกต์ (N)', rom: 'bpə̀ət / bpìt sǐang ɛ-fék (N)' },
  'btn.music': { en: 'Music on / off (M)', th: 'เปิด/ปิดเพลง (M)', rom: 'bpə̀ət / bpìt phleeng (M)' },
  'btn.next': { en: 'Next track (.)', th: 'เพลงถัดไป (.)' },
  'btn.menu': { en: 'Menu (Esc)', th: 'เมนู (Esc)' },
  'btn.snackbook': { en: 'Snack Book (B)', th: 'สมุดขนม (B)' },

  // ---------------------------------------------------------------- pause menu
  'menu.resumeStore': { en: 'Back to the store', th: 'กลับเข้าร้าน', rom: 'glàp kâo ráan' },
  'menu.about': { en: 'About', th: 'เกี่ยวกับเกม', rom: 'gìao-gàp gem' },
  'pause.sound': { en: 'Sound', th: 'เสียง', rom: 'sǐang' },
  'pause.sfx': { en: 'Sound effects', th: 'เสียงเอฟเฟกต์', rom: 'sǐang ɛ-fék' },
  'pause.music': { en: 'Music', th: 'เพลง', rom: 'phleeng' },
  'pause.tracks': { en: 'Music track', th: 'เลือกเพลง', rom: 'lûak phleeng' },
  'pause.musicVol': { en: 'Music volume', th: 'ระดับเพลง', rom: 'rá-dàp phleeng' },
  'pause.sfxVol': { en: 'Effects volume', th: 'ระดับเสียง', rom: 'rá-dàp sǐang' },
  'pause.language': { en: 'Language', th: 'ภาษา', rom: 'paa-sǎa' },
  'track.bright': { en: 'Bright, bouncy', th: 'สดใส กระฉับกระเฉง', rom: 'sòt-sǎi grà-chàp-grà-chə̌ng' },
  'track.funky': { en: 'Funky, head-bob pace', th: 'จังหวะสนุก โยกหัวตาม', rom: 'jang-wà sà-nùk yôok hǔa dtaam' },
  'track.sunny': { en: 'Fast and sunny', th: 'เร็วและสดใส', rom: 'reo lɛ́ sòt-sǎi' },
  'track.dreamy': { en: 'Slow and dreamy', th: 'ช้าและฝันหวาน', rom: 'cháa lɛ́ fǎn-wǎan' },
  'toast.soundOff': { en: 'Sound effects off', th: 'ปิดเสียงเอฟเฟกต์แล้ว', rom: 'bpìt sǐang ɛ-fék lɛ́ɛo' },
  'toast.soundOn': { en: 'Sound effects on', th: 'เปิดเสียงเอฟเฟกต์แล้ว', rom: 'bpə̀ət sǐang ɛ-fék lɛ́ɛo' },
  'toast.musicOff': { en: 'Music off', th: 'ปิดเพลงแล้ว', rom: 'bpìt phleeng lɛ́ɛo' },
  'toast.musicOn': { en: 'Music on', th: 'เปิดเพลงแล้ว', rom: 'bpə̀ət phleeng lɛ́ɛo' },
  'toast.track': { en: 'Now playing: {name}', th: 'กำลังเล่น: {name}', rom: 'gam-lang lên: {name}' },
  'set.track': { en: 'Music track', th: 'เลือกเพลง' },
  'set.musicOn': { en: 'Music', th: 'เพลง' },
  'set.muted': { en: 'Sound effects off (music keeps playing)', th: 'ปิดเสียงเอฟเฟกต์ (เพลงยังเล่นอยู่)', rom: 'bpìt sǐang ɛ-fék (phleeng yang lên yùu)' },

  // ---------------------------------------------------------------- controls panel
  'ctlg.move': { en: 'Move & look', th: 'เดินและมอง', rom: 'dəən lɛ́ mɔɔng' },
  'ctlg.shop': { en: 'Shop', th: 'ช็อปปิ้ง', rom: 'chɔ́p-bpîng' },
  'ctlg.stuff': { en: 'Your stuff', th: 'ของฉัน', rom: 'kɔ̌ɔng chǎn' },
  'ctlg.game': { en: 'Game & sound', th: 'เกมและเสียง', rom: 'gem lɛ́ sǐang' },
  'ctl.tab.kb': { en: 'Keyboard', th: 'คีย์บอร์ด', rom: 'kii-bɔ̀ɔt' },
  'ctl.tab.touch': { en: 'Touch', th: 'ทัชสกรีน', rom: 'tát-sà-grin' },
  'ctl.or': { en: 'or', th: 'หรือ', rom: 'rʉ̌ʉ' },
  'ctl.take1': { en: 'Take', th: 'หยิบ', rom: 'yìp' },
  'ctl.use': { en: 'Talk / use', th: 'คุย / ใช้งาน', rom: 'kui / chái-ngaan' },
  'ctl.codex': { en: 'Snack Book', th: 'สมุดขนม', rom: 'sà-mùt kà-nǒm' },
  'ctl.mute': { en: 'Sound effects on / off', th: 'เปิด/ปิดเสียงเอฟเฟกต์', rom: 'bpə̀ət/bpìt sǐang ɛ-fék' },
  'ctl.music': { en: 'Music on / off', th: 'เปิด/ปิดเพลง', rom: 'bpə̀ət / bpìt phleeng' },
  'ctl.next': { en: 'Next track', th: 'เพลงถัดไป', rom: 'phleeng tàt-bpai' },
  'ctl.crouch': { en: 'Crouch (low shelves)', th: 'ย่อตัว (ดูชั้นล่าง)', rom: 'yɔ̂ɔ dtua (duu chán lâang)' },
  'ctl.zoom': { en: 'Zoom to read labels', th: 'ซูมอ่านฉลาก', rom: 'suum àan chà-làak' },
  'ctl.flip': { en: 'Flip pack (when inspecting)', th: 'พลิกหน้า/หลังซอง', rom: 'plìk nâa / lǎng sɔɔng' },
  'ctl.mouse': { en: 'Mouse', th: 'เมาส์', rom: 'máo' },
  'ctl.tip': { en: 'Tip: press H in game to hide the hint bar.', th: 'เคล็ดลับ: กด H เพื่อซ่อนแถบคำแนะนำ' },
  'tch.stick': { en: 'Left thumb: drag', th: 'ลากนิ้วซ้าย', rom: 'lâak níu sáai' },
  'tch.stickD': { en: 'Walk. Push to the edge to sprint.', th: 'เดิน ดันสุดขอบเพื่อวิ่ง', rom: 'dəən, dan sùt kɔ̀ɔp pʉ̂a wîng' },
  'tch.look': { en: 'Right side: drag', th: 'ลากด้านขวา', rom: 'lâak dâan kwǎa' },
  'tch.lookD': { en: 'Look around', th: 'มองรอบตัว', rom: 'mɔɔng rɔ̂ɔp dtua' },
  'tch.pinch': { en: 'Two fingers: pinch', th: 'บีบสองนิ้ว', rom: 'bìip sɔ̌ɔng níu' },
  'tch.pinchD': { en: 'Zoom in to read labels', th: 'ซูมอ่านฉลาก', rom: 'suum àan chà-làak' },
  'tch.crouch': { en: 'Crouch button', th: 'ปุ่มย่อตัว', rom: 'bpùm yɔ̂ɔ dtua' },
  'tch.crouchD': { en: 'Reach the low shelves', th: 'ดูชั้นล่าง', rom: 'duu chán lâang' },
  'tch.take': { en: 'Take', th: 'หยิบ', rom: 'yìp' },
  'tch.takeD': { en: 'Grab the item you are looking at', th: 'หยิบสินค้าที่มอง', rom: 'yìp sǐn-káa tîi mɔɔng' },
  'tch.inspect': { en: 'Inspect', th: 'ดูใกล้ๆ', rom: 'duu glâi-glâi' },
  'tch.inspectD': { en: 'Look closely, drag to turn it', th: 'ดูใกล้ๆ ลากเพื่อหมุน', rom: 'duu glâi-glâi, lâak pʉ̂a mǔn' },
  'tch.back': { en: 'Put back', th: 'วางคืน', rom: 'waang kʉʉn' },
  'tch.backD': { en: 'Return the last item', th: 'วางสินค้าชิ้นล่าสุดคืน', rom: 'waang sǐn-káa chín lâ-sùt kʉʉn' },
  'tch.basket': { en: 'Basket', th: 'ตะกร้า', rom: 'dtà-grâa' },
  'tch.basketD': { en: 'See what you are carrying', th: 'ดูของในตะกร้า', rom: 'duu kɔ̌ɔng nai dtà-grâa' },
  'tch.snack': { en: 'Snack Book chip', th: 'ชิปสมุดขนม', rom: 'chíp sà-mùt kà-nǒm' },
  'tch.snackD': { en: 'Top bar, or the pause menu', th: 'แถบด้านบน หรือเมนูหยุด', rom: 'tɛ̀ɛp dâan bon rʉ̌ʉ me-nuu yùt' },
  'tch.audioD': { en: 'Sound, music and tracks live in the menu', th: 'เสียง เพลง อยู่ในเมนู', rom: 'sǐang phleeng yùu nai me-nuu' },
  'tch.menu': { en: 'Menu button', th: 'ปุ่มเมนู', rom: 'bpùm me-nuu' },
  'tch.menuD': { en: 'Pause, sound, language, settings', th: 'หยุด เสียง ภาษา ตั้งค่า', rom: 'yùt sǐang paa-sǎa dtâng-kâa' },

  // ---------------------------------------------------------------- about + badge
  'about.game': { en: 'About the game', th: 'เกี่ยวกับเกม', rom: 'gìao-gàp gem' },
  'about.role': { en: 'Store Creator', th: 'ผู้สร้างร้าน', rom: 'pûu sâang ráan' },
  'about.employee': { en: 'EMPLOYEE', th: 'พนักงาน', rom: 'pá-nák-ngaan' },
  'about.id': { en: 'ID NO.', th: 'รหัส', rom: 'rá-hàt' },
  'about.shift': { en: 'SHIFT', th: 'กะ', rom: 'gà' },
  'about.shiftVal': { en: 'Night · 24 hrs', th: 'ดึก · 24 ชม.', rom: 'dùek · yii-sìp-sìi chûa-moong' },
  'about.base': { en: 'BASE', th: 'ประจำที่', rom: 'bprà-jam tîi' },
  'about.baseVal': { en: 'Bangkok', th: 'กรุงเทพฯ', rom: 'grung-têep' },
  'about.tagline': { en: '“I like seven 24/7!”', th: '“ชอบเซเว่น 24/7!”', rom: 'chɔ̂ɔp sé-wên 24/7' },
  'about.find': { en: 'Find Nomaditsu', th: 'ติดตามได้ที่', rom: 'dtìt-dtaam dâai tîi' },
  'about.musicH': { en: 'Listen to my music', th: 'ฟังเพลงของฉัน', rom: 'fang phleeng kɔ̌ɔng chǎn' },
  'about.tipH': { en: 'Tip the cashier', th: 'ทิปให้แคชเชียร์', rom: 'típ hâi kɛ́ɛt-chia' },
  'about.tipText': { en: 'Free and open source. If this made your night, you can buy me a coffee.', th: 'ฟรีและโอเพนซอร์ส ถ้าเกมนี้ทำให้คุณมีความสุข เลี้ยงกาแฟฉันสักแก้วได้นะ', rom: 'frii lɛ́ oo-pən-sɔ́ɔt, tâa gem níi tam-hâi kun mii kwaam-sùk, líang gaa-fɛɛ chǎn sàk gɛ̂ɛo dâai ná' },
  'about.fineH': { en: 'The fine print', th: 'ข้อความสำคัญ', rom: 'kɔ̂ɔ-kwaam sǎm-kan' },
  'about.oss': {
    en: 'Open-source credits: three.js (MIT license) and the fonts Kanit, Mitr, Sarabun, Mali, Pattaya, Chonburi, Sriracha, Itim, Anton, Bebas Neue, Lilita One, Pacifico, Bangers, Archivo Black, Righteous and Fredoka (SIL Open Font License 1.1). The full license texts are inside index.html.',
    th: 'เครดิตโอเพนซอร์ส: three.js (ไลเซนส์ MIT) และฟอนต์ Kanit, Mitr, Sarabun, Mali, Pattaya, Chonburi, Sriracha, Itim, Anton, Bebas Neue, Lilita One, Pacifico, Bangers, Archivo Black, Righteous และ Fredoka (ไลเซนส์ SIL Open Font License 1.1) ข้อความไลเซนส์ฉบับเต็มอยู่ในไฟล์ index.html',
    rom: 'kree-dìt oo-pən-sɔ́ɔt: three.js (lái-sɛn MIT) lɛ́ fɔn Kanit, Mitr, Sarabun, Mali, Pattaya, Chonburi, Sriracha, Itim, Anton, Bebas Neue, Lilita One, Pacifico, Bangers, Archivo Black, Righteous lɛ́ Fredoka (lái-sɛn SIL Open Font License 1.1), kɔ̂ɔ-kwaam lái-sɛn chà-bàp dtem yùu nai fai index.html' },
  'about.credit': {
    en: 'Made with love by Ray de Guzman aka @nomaditsu with $200 of Claude Sonnet 5.5 in Claude Code with three.js on 2026-09-29. Now yours free, fully open-sourced with an MIT license.',
    th: 'สร้างด้วยความรักโดย Ray de Guzman หรือ @nomaditsu ด้วย Claude Sonnet 5.5 มูลค่า 200 ดอลลาร์ ใน Claude Code กับ three.js เมื่อ 2026-09-29 ตอนนี้เป็นของคุณแล้ว ฟรี โอเพนซอร์สเต็มรูปแบบภายใต้ไลเซนส์ MIT',
    rom: 'sâang dûai kwaam-rák dooi Ray de Guzman rʉ̌ʉ @nomaditsu dûai Claude Sonnet 5.5 muun-la-kâa sɔ̌ɔng-rɔ́ɔi dɔn-lâa nai Claude Code gàp three.js mʉ̂a 2026-09-29 dtɔɔn-níi bpen kɔ̌ɔng kun lɛ́ɛo, frii, oo-pən-sɔ́ɔt dtem-rûup-bɛ̀ɛp pâai-dtâi lái-sɛn MIT' },

  // ---------------------------------------------------------------- talking
  'talk.leave': { en: 'Leave', th: 'ออก', rom: 'ɔ̀ɔk' },
  'talk.goodbye': { en: 'Goodbye', th: 'ลาก่อน', rom: 'laa-gɔ̀ɔn' },
  'talk.voiceOn': { en: 'Voice on', th: 'เสียงเปิด', rom: 'sǐang bpə̀ət' },
  'talk.voiceOff': { en: 'Voice off', th: 'เสียงปิด', rom: 'sǐang bpìt' },
  'talk.continue': { en: 'Continue', th: 'ต่อไป', rom: 'dtɔ̀ɔ-bpai' },
  'ach.friendly': { en: 'Friendly Regular', th: 'ขาประจำใจดี', rom: 'kǎa-bprà-jam jai-dii' },
  'ach.friendlyDesc': { en: 'Chat with everyone in the store.', th: 'คุยกับทุกคนในร้าน', rom: 'kui gàp túk kon nai ráan' },
  'ach.tipper': { en: 'Good Tipper', th: 'ใจดีให้ทิป', rom: 'jai-dii hâi típ' },
  'ach.tipperDesc': { en: 'Say thanks the Thai way.', th: 'ขอบคุณแบบไทยๆ', rom: 'kɔ̀ɔp-kun bɛ̀ɛp tai-tai' },
};
